// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: flow-messages-enriched.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Flowmessageenriched {

  /// <summary>Holder for reflection information generated from flow-messages-enriched.proto</summary>
  public static partial class FlowMessagesEnrichedReflection {

    #region Descriptor
    /// <summary>File descriptor for flow-messages-enriched.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FlowMessagesEnrichedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxmbG93LW1lc3NhZ2VzLWVucmljaGVkLnByb3RvEhNmbG93bWVzc2FnZWVu",
            "cmljaGVkIrwICgtGbG93TWVzc2FnZRI3CgRUeXBlGAEgASgOMikuZmxvd21l",
            "c3NhZ2VlbnJpY2hlZC5GbG93TWVzc2FnZS5GbG93VHlwZRIRCglUaW1lUmVj",
            "dmQYAiABKAQSFAoMU2FtcGxpbmdSYXRlGAMgASgEEhMKC1NlcXVlbmNlTnVt",
            "GAQgASgNEhAKCFRpbWVGbG93GAUgASgEEg0KBVNyY0lQGAYgASgMEg0KBURz",
            "dElQGAcgASgMEjoKCUlQdmVyc2lvbhgIIAEoDjInLmZsb3dtZXNzYWdlZW5y",
            "aWNoZWQuRmxvd01lc3NhZ2UuSVBUeXBlEg0KBUJ5dGVzGAkgASgEEg8KB1Bh",
            "Y2tldHMYCiABKAQSEgoKUm91dGVyQWRkchgLIAEoDBIPCgdOZXh0SG9wGAwg",
            "ASgMEhEKCU5leHRIb3BBUxgNIAEoDRINCgVTcmNBUxgOIAEoDRINCgVEc3RB",
            "UxgPIAEoDRIOCgZTcmNOZXQYECABKA0SDgoGRHN0TmV0GBEgASgNEg0KBVNy",
            "Y0lmGBIgASgNEg0KBURzdElmGBMgASgNEg0KBVByb3RvGBQgASgNEg8KB1Ny",
            "Y1BvcnQYFSABKA0SDwoHRHN0UG9ydBgWIAEoDRINCgVJUFRvcxgXIAEoDRIY",
            "ChBGb3J3YXJkaW5nU3RhdHVzGBggASgNEg0KBUlQVFRMGBkgASgNEhAKCFRD",
            "UEZsYWdzGBogASgNEg4KBlNyY01hYxgbIAEoBBIOCgZEc3RNYWMYHCABKAQS",
            "DgoGVmxhbklkGB0gASgNEg0KBUV0eXBlGB4gASgNEkEKCURpcmVjdGlvbhha",
            "IAEoDjIuLmZsb3dtZXNzYWdlZW5yaWNoZWQuRmxvd01lc3NhZ2UuRGlyZWN0",
            "aW9uVHlwZRILCgNDaWQYWyABKA0SQwoKTm9ybWFsaXplZBhcIAEoDjIvLmZs",
            "b3dtZXNzYWdlZW5yaWNoZWQuRmxvd01lc3NhZ2UuTm9ybWFsaXplZFR5cGUS",
            "EQoJU3JjSWZOYW1lGF0gASgJEhEKCVNyY0lmRGVzYxheIAEoCRISCgpTcmNJ",
            "ZlNwZWVkGF8gASgNEhEKCURzdElmTmFtZRhgIAEoCRIRCglEc3RJZkRlc2MY",
            "YSABKAkSEgoKRHN0SWZTcGVlZBhiIAEoDRIMCgRQZWVyGGMgASgJIjsKCEZs",
            "b3dUeXBlEg8KC0ZMT1dVTktOT1dOEAASCAoETkZWORAJEgkKBUlQRklYEAoS",
            "CQoFU0ZMT1cQBSIrCgZJUFR5cGUSDQoJSVBVTktOT1dOEAASCAoESVB2NBAE",
            "EggKBElQdjYQBiI4Cg1EaXJlY3Rpb25UeXBlEgsKB1Vua25vd24QABIMCghJ",
            "bmNvbWluZxABEgwKCE91dGdvaW5nEAIiIQoOTm9ybWFsaXplZFR5cGUSBgoC",
            "Tm8QABIHCgNZZXMQAUIaCglid25ldGZsb3dCDUZsb3dNZXNzYWdlUGJiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Flowmessageenriched.FlowMessage), global::Flowmessageenriched.FlowMessage.Parser, new[]{ "Type", "TimeRecvd", "SamplingRate", "SequenceNum", "TimeFlow", "SrcIP", "DstIP", "IPversion", "Bytes", "Packets", "RouterAddr", "NextHop", "NextHopAS", "SrcAS", "DstAS", "SrcNet", "DstNet", "SrcIf", "DstIf", "Proto", "SrcPort", "DstPort", "IPTos", "ForwardingStatus", "IPTTL", "TCPFlags", "SrcMac", "DstMac", "VlanId", "Etype", "Direction", "Cid", "Normalized", "SrcIfName", "SrcIfDesc", "SrcIfSpeed", "DstIfName", "DstIfDesc", "DstIfSpeed", "Peer" }, null, new[]{ typeof(global::Flowmessageenriched.FlowMessage.Types.FlowType), typeof(global::Flowmessageenriched.FlowMessage.Types.IPType), typeof(global::Flowmessageenriched.FlowMessage.Types.DirectionType), typeof(global::Flowmessageenriched.FlowMessage.Types.NormalizedType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Flow Message needs to stay compatible to goflow's default protobuf
  /// -> never edit record id's, only ever append
  /// </summary>
  public sealed partial class FlowMessage : pb::IMessage<FlowMessage> {
    private static readonly pb::MessageParser<FlowMessage> _parser = new pb::MessageParser<FlowMessage>(() => new FlowMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FlowMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Flowmessageenriched.FlowMessagesEnrichedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlowMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlowMessage(FlowMessage other) : this() {
      type_ = other.type_;
      timeRecvd_ = other.timeRecvd_;
      samplingRate_ = other.samplingRate_;
      sequenceNum_ = other.sequenceNum_;
      timeFlow_ = other.timeFlow_;
      srcIP_ = other.srcIP_;
      dstIP_ = other.dstIP_;
      iPversion_ = other.iPversion_;
      bytes_ = other.bytes_;
      packets_ = other.packets_;
      routerAddr_ = other.routerAddr_;
      nextHop_ = other.nextHop_;
      nextHopAS_ = other.nextHopAS_;
      srcAS_ = other.srcAS_;
      dstAS_ = other.dstAS_;
      srcNet_ = other.srcNet_;
      dstNet_ = other.dstNet_;
      srcIf_ = other.srcIf_;
      dstIf_ = other.dstIf_;
      proto_ = other.proto_;
      srcPort_ = other.srcPort_;
      dstPort_ = other.dstPort_;
      iPTos_ = other.iPTos_;
      forwardingStatus_ = other.forwardingStatus_;
      iPTTL_ = other.iPTTL_;
      tCPFlags_ = other.tCPFlags_;
      srcMac_ = other.srcMac_;
      dstMac_ = other.dstMac_;
      vlanId_ = other.vlanId_;
      etype_ = other.etype_;
      direction_ = other.direction_;
      cid_ = other.cid_;
      normalized_ = other.normalized_;
      srcIfName_ = other.srcIfName_;
      srcIfDesc_ = other.srcIfDesc_;
      srcIfSpeed_ = other.srcIfSpeed_;
      dstIfName_ = other.dstIfName_;
      dstIfDesc_ = other.dstIfDesc_;
      dstIfSpeed_ = other.dstIfSpeed_;
      peer_ = other.peer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlowMessage Clone() {
      return new FlowMessage(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Flowmessageenriched.FlowMessage.Types.FlowType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Flowmessageenriched.FlowMessage.Types.FlowType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "TimeRecvd" field.</summary>
    public const int TimeRecvdFieldNumber = 2;
    private ulong timeRecvd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong TimeRecvd {
      get { return timeRecvd_; }
      set {
        timeRecvd_ = value;
      }
    }

    /// <summary>Field number for the "SamplingRate" field.</summary>
    public const int SamplingRateFieldNumber = 3;
    private ulong samplingRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong SamplingRate {
      get { return samplingRate_; }
      set {
        samplingRate_ = value;
      }
    }

    /// <summary>Field number for the "SequenceNum" field.</summary>
    public const int SequenceNumFieldNumber = 4;
    private uint sequenceNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SequenceNum {
      get { return sequenceNum_; }
      set {
        sequenceNum_ = value;
      }
    }

    /// <summary>Field number for the "TimeFlow" field.</summary>
    public const int TimeFlowFieldNumber = 5;
    private ulong timeFlow_;
    /// <summary>
    /// Found inside packet
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong TimeFlow {
      get { return timeFlow_; }
      set {
        timeFlow_ = value;
      }
    }

    /// <summary>Field number for the "SrcIP" field.</summary>
    public const int SrcIPFieldNumber = 6;
    private pb::ByteString srcIP_ = pb::ByteString.Empty;
    /// <summary>
    /// Source/destination addresses
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SrcIP {
      get { return srcIP_; }
      set {
        srcIP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DstIP" field.</summary>
    public const int DstIPFieldNumber = 7;
    private pb::ByteString dstIP_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString DstIP {
      get { return dstIP_; }
      set {
        dstIP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IPversion" field.</summary>
    public const int IPversionFieldNumber = 8;
    private global::Flowmessageenriched.FlowMessage.Types.IPType iPversion_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Flowmessageenriched.FlowMessage.Types.IPType IPversion {
      get { return iPversion_; }
      set {
        iPversion_ = value;
      }
    }

    /// <summary>Field number for the "Bytes" field.</summary>
    public const int BytesFieldNumber = 9;
    private ulong bytes_;
    /// <summary>
    /// Size of the sampled packet
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Bytes {
      get { return bytes_; }
      set {
        bytes_ = value;
      }
    }

    /// <summary>Field number for the "Packets" field.</summary>
    public const int PacketsFieldNumber = 10;
    private ulong packets_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Packets {
      get { return packets_; }
      set {
        packets_ = value;
      }
    }

    /// <summary>Field number for the "RouterAddr" field.</summary>
    public const int RouterAddrFieldNumber = 11;
    private pb::ByteString routerAddr_ = pb::ByteString.Empty;
    /// <summary>
    /// Routing information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString RouterAddr {
      get { return routerAddr_; }
      set {
        routerAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NextHop" field.</summary>
    public const int NextHopFieldNumber = 12;
    private pb::ByteString nextHop_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString NextHop {
      get { return nextHop_; }
      set {
        nextHop_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NextHopAS" field.</summary>
    public const int NextHopASFieldNumber = 13;
    private uint nextHopAS_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint NextHopAS {
      get { return nextHopAS_; }
      set {
        nextHopAS_ = value;
      }
    }

    /// <summary>Field number for the "SrcAS" field.</summary>
    public const int SrcASFieldNumber = 14;
    private uint srcAS_;
    /// <summary>
    /// Autonomous system information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcAS {
      get { return srcAS_; }
      set {
        srcAS_ = value;
      }
    }

    /// <summary>Field number for the "DstAS" field.</summary>
    public const int DstASFieldNumber = 15;
    private uint dstAS_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstAS {
      get { return dstAS_; }
      set {
        dstAS_ = value;
      }
    }

    /// <summary>Field number for the "SrcNet" field.</summary>
    public const int SrcNetFieldNumber = 16;
    private uint srcNet_;
    /// <summary>
    /// Prefix size
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcNet {
      get { return srcNet_; }
      set {
        srcNet_ = value;
      }
    }

    /// <summary>Field number for the "DstNet" field.</summary>
    public const int DstNetFieldNumber = 17;
    private uint dstNet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstNet {
      get { return dstNet_; }
      set {
        dstNet_ = value;
      }
    }

    /// <summary>Field number for the "SrcIf" field.</summary>
    public const int SrcIfFieldNumber = 18;
    private uint srcIf_;
    /// <summary>
    /// Interfaces
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcIf {
      get { return srcIf_; }
      set {
        srcIf_ = value;
      }
    }

    /// <summary>Field number for the "DstIf" field.</summary>
    public const int DstIfFieldNumber = 19;
    private uint dstIf_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstIf {
      get { return dstIf_; }
      set {
        dstIf_ = value;
      }
    }

    /// <summary>Field number for the "Proto" field.</summary>
    public const int ProtoFieldNumber = 20;
    private uint proto_;
    /// <summary>
    /// Layer 4 protocol
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Proto {
      get { return proto_; }
      set {
        proto_ = value;
      }
    }

    /// <summary>Field number for the "SrcPort" field.</summary>
    public const int SrcPortFieldNumber = 21;
    private uint srcPort_;
    /// <summary>
    /// Port for UDP and TCP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcPort {
      get { return srcPort_; }
      set {
        srcPort_ = value;
      }
    }

    /// <summary>Field number for the "DstPort" field.</summary>
    public const int DstPortFieldNumber = 22;
    private uint dstPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstPort {
      get { return dstPort_; }
      set {
        dstPort_ = value;
      }
    }

    /// <summary>Field number for the "IPTos" field.</summary>
    public const int IPTosFieldNumber = 23;
    private uint iPTos_;
    /// <summary>
    /// IP and TCP special flags
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IPTos {
      get { return iPTos_; }
      set {
        iPTos_ = value;
      }
    }

    /// <summary>Field number for the "ForwardingStatus" field.</summary>
    public const int ForwardingStatusFieldNumber = 24;
    private uint forwardingStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ForwardingStatus {
      get { return forwardingStatus_; }
      set {
        forwardingStatus_ = value;
      }
    }

    /// <summary>Field number for the "IPTTL" field.</summary>
    public const int IPTTLFieldNumber = 25;
    private uint iPTTL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IPTTL {
      get { return iPTTL_; }
      set {
        iPTTL_ = value;
      }
    }

    /// <summary>Field number for the "TCPFlags" field.</summary>
    public const int TCPFlagsFieldNumber = 26;
    private uint tCPFlags_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint TCPFlags {
      get { return tCPFlags_; }
      set {
        tCPFlags_ = value;
      }
    }

    /// <summary>Field number for the "SrcMac" field.</summary>
    public const int SrcMacFieldNumber = 27;
    private ulong srcMac_;
    /// <summary>
    /// Ethernet information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong SrcMac {
      get { return srcMac_; }
      set {
        srcMac_ = value;
      }
    }

    /// <summary>Field number for the "DstMac" field.</summary>
    public const int DstMacFieldNumber = 28;
    private ulong dstMac_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong DstMac {
      get { return dstMac_; }
      set {
        dstMac_ = value;
      }
    }

    /// <summary>Field number for the "VlanId" field.</summary>
    public const int VlanIdFieldNumber = 29;
    private uint vlanId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint VlanId {
      get { return vlanId_; }
      set {
        vlanId_ = value;
      }
    }

    /// <summary>Field number for the "Etype" field.</summary>
    public const int EtypeFieldNumber = 30;
    private uint etype_;
    /// <summary>
    /// Layer 3 protocol (IPv4/IPv6/ARP/...)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Etype {
      get { return etype_; }
      set {
        etype_ = value;
      }
    }

    /// <summary>Field number for the "Direction" field.</summary>
    public const int DirectionFieldNumber = 90;
    private global::Flowmessageenriched.FlowMessage.Types.DirectionType direction_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Flowmessageenriched.FlowMessage.Types.DirectionType Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "Cid" field.</summary>
    public const int CidFieldNumber = 91;
    private uint cid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Cid {
      get { return cid_; }
      set {
        cid_ = value;
      }
    }

    /// <summary>Field number for the "Normalized" field.</summary>
    public const int NormalizedFieldNumber = 92;
    private global::Flowmessageenriched.FlowMessage.Types.NormalizedType normalized_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Flowmessageenriched.FlowMessage.Types.NormalizedType Normalized {
      get { return normalized_; }
      set {
        normalized_ = value;
      }
    }

    /// <summary>Field number for the "SrcIfName" field.</summary>
    public const int SrcIfNameFieldNumber = 93;
    private string srcIfName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SrcIfName {
      get { return srcIfName_; }
      set {
        srcIfName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SrcIfDesc" field.</summary>
    public const int SrcIfDescFieldNumber = 94;
    private string srcIfDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SrcIfDesc {
      get { return srcIfDesc_; }
      set {
        srcIfDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SrcIfSpeed" field.</summary>
    public const int SrcIfSpeedFieldNumber = 95;
    private uint srcIfSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcIfSpeed {
      get { return srcIfSpeed_; }
      set {
        srcIfSpeed_ = value;
      }
    }

    /// <summary>Field number for the "DstIfName" field.</summary>
    public const int DstIfNameFieldNumber = 96;
    private string dstIfName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DstIfName {
      get { return dstIfName_; }
      set {
        dstIfName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DstIfDesc" field.</summary>
    public const int DstIfDescFieldNumber = 97;
    private string dstIfDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DstIfDesc {
      get { return dstIfDesc_; }
      set {
        dstIfDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DstIfSpeed" field.</summary>
    public const int DstIfSpeedFieldNumber = 98;
    private uint dstIfSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstIfSpeed {
      get { return dstIfSpeed_; }
      set {
        dstIfSpeed_ = value;
      }
    }

    /// <summary>Field number for the "Peer" field.</summary>
    public const int PeerFieldNumber = 99;
    private string peer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Peer {
      get { return peer_; }
      set {
        peer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FlowMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FlowMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (TimeRecvd != other.TimeRecvd) return false;
      if (SamplingRate != other.SamplingRate) return false;
      if (SequenceNum != other.SequenceNum) return false;
      if (TimeFlow != other.TimeFlow) return false;
      if (SrcIP != other.SrcIP) return false;
      if (DstIP != other.DstIP) return false;
      if (IPversion != other.IPversion) return false;
      if (Bytes != other.Bytes) return false;
      if (Packets != other.Packets) return false;
      if (RouterAddr != other.RouterAddr) return false;
      if (NextHop != other.NextHop) return false;
      if (NextHopAS != other.NextHopAS) return false;
      if (SrcAS != other.SrcAS) return false;
      if (DstAS != other.DstAS) return false;
      if (SrcNet != other.SrcNet) return false;
      if (DstNet != other.DstNet) return false;
      if (SrcIf != other.SrcIf) return false;
      if (DstIf != other.DstIf) return false;
      if (Proto != other.Proto) return false;
      if (SrcPort != other.SrcPort) return false;
      if (DstPort != other.DstPort) return false;
      if (IPTos != other.IPTos) return false;
      if (ForwardingStatus != other.ForwardingStatus) return false;
      if (IPTTL != other.IPTTL) return false;
      if (TCPFlags != other.TCPFlags) return false;
      if (SrcMac != other.SrcMac) return false;
      if (DstMac != other.DstMac) return false;
      if (VlanId != other.VlanId) return false;
      if (Etype != other.Etype) return false;
      if (Direction != other.Direction) return false;
      if (Cid != other.Cid) return false;
      if (Normalized != other.Normalized) return false;
      if (SrcIfName != other.SrcIfName) return false;
      if (SrcIfDesc != other.SrcIfDesc) return false;
      if (SrcIfSpeed != other.SrcIfSpeed) return false;
      if (DstIfName != other.DstIfName) return false;
      if (DstIfDesc != other.DstIfDesc) return false;
      if (DstIfSpeed != other.DstIfSpeed) return false;
      if (Peer != other.Peer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (TimeRecvd != 0UL) hash ^= TimeRecvd.GetHashCode();
      if (SamplingRate != 0UL) hash ^= SamplingRate.GetHashCode();
      if (SequenceNum != 0) hash ^= SequenceNum.GetHashCode();
      if (TimeFlow != 0UL) hash ^= TimeFlow.GetHashCode();
      if (SrcIP.Length != 0) hash ^= SrcIP.GetHashCode();
      if (DstIP.Length != 0) hash ^= DstIP.GetHashCode();
      if (IPversion != 0) hash ^= IPversion.GetHashCode();
      if (Bytes != 0UL) hash ^= Bytes.GetHashCode();
      if (Packets != 0UL) hash ^= Packets.GetHashCode();
      if (RouterAddr.Length != 0) hash ^= RouterAddr.GetHashCode();
      if (NextHop.Length != 0) hash ^= NextHop.GetHashCode();
      if (NextHopAS != 0) hash ^= NextHopAS.GetHashCode();
      if (SrcAS != 0) hash ^= SrcAS.GetHashCode();
      if (DstAS != 0) hash ^= DstAS.GetHashCode();
      if (SrcNet != 0) hash ^= SrcNet.GetHashCode();
      if (DstNet != 0) hash ^= DstNet.GetHashCode();
      if (SrcIf != 0) hash ^= SrcIf.GetHashCode();
      if (DstIf != 0) hash ^= DstIf.GetHashCode();
      if (Proto != 0) hash ^= Proto.GetHashCode();
      if (SrcPort != 0) hash ^= SrcPort.GetHashCode();
      if (DstPort != 0) hash ^= DstPort.GetHashCode();
      if (IPTos != 0) hash ^= IPTos.GetHashCode();
      if (ForwardingStatus != 0) hash ^= ForwardingStatus.GetHashCode();
      if (IPTTL != 0) hash ^= IPTTL.GetHashCode();
      if (TCPFlags != 0) hash ^= TCPFlags.GetHashCode();
      if (SrcMac != 0UL) hash ^= SrcMac.GetHashCode();
      if (DstMac != 0UL) hash ^= DstMac.GetHashCode();
      if (VlanId != 0) hash ^= VlanId.GetHashCode();
      if (Etype != 0) hash ^= Etype.GetHashCode();
      if (Direction != 0) hash ^= Direction.GetHashCode();
      if (Cid != 0) hash ^= Cid.GetHashCode();
      if (Normalized != 0) hash ^= Normalized.GetHashCode();
      if (SrcIfName.Length != 0) hash ^= SrcIfName.GetHashCode();
      if (SrcIfDesc.Length != 0) hash ^= SrcIfDesc.GetHashCode();
      if (SrcIfSpeed != 0) hash ^= SrcIfSpeed.GetHashCode();
      if (DstIfName.Length != 0) hash ^= DstIfName.GetHashCode();
      if (DstIfDesc.Length != 0) hash ^= DstIfDesc.GetHashCode();
      if (DstIfSpeed != 0) hash ^= DstIfSpeed.GetHashCode();
      if (Peer.Length != 0) hash ^= Peer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (TimeRecvd != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(TimeRecvd);
      }
      if (SamplingRate != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(SamplingRate);
      }
      if (SequenceNum != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(SequenceNum);
      }
      if (TimeFlow != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(TimeFlow);
      }
      if (SrcIP.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(SrcIP);
      }
      if (DstIP.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(DstIP);
      }
      if (IPversion != 0) {
        output.WriteRawTag(64);
        output.WriteEnum((int) IPversion);
      }
      if (Bytes != 0UL) {
        output.WriteRawTag(72);
        output.WriteUInt64(Bytes);
      }
      if (Packets != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(Packets);
      }
      if (RouterAddr.Length != 0) {
        output.WriteRawTag(90);
        output.WriteBytes(RouterAddr);
      }
      if (NextHop.Length != 0) {
        output.WriteRawTag(98);
        output.WriteBytes(NextHop);
      }
      if (NextHopAS != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(NextHopAS);
      }
      if (SrcAS != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(SrcAS);
      }
      if (DstAS != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(DstAS);
      }
      if (SrcNet != 0) {
        output.WriteRawTag(128, 1);
        output.WriteUInt32(SrcNet);
      }
      if (DstNet != 0) {
        output.WriteRawTag(136, 1);
        output.WriteUInt32(DstNet);
      }
      if (SrcIf != 0) {
        output.WriteRawTag(144, 1);
        output.WriteUInt32(SrcIf);
      }
      if (DstIf != 0) {
        output.WriteRawTag(152, 1);
        output.WriteUInt32(DstIf);
      }
      if (Proto != 0) {
        output.WriteRawTag(160, 1);
        output.WriteUInt32(Proto);
      }
      if (SrcPort != 0) {
        output.WriteRawTag(168, 1);
        output.WriteUInt32(SrcPort);
      }
      if (DstPort != 0) {
        output.WriteRawTag(176, 1);
        output.WriteUInt32(DstPort);
      }
      if (IPTos != 0) {
        output.WriteRawTag(184, 1);
        output.WriteUInt32(IPTos);
      }
      if (ForwardingStatus != 0) {
        output.WriteRawTag(192, 1);
        output.WriteUInt32(ForwardingStatus);
      }
      if (IPTTL != 0) {
        output.WriteRawTag(200, 1);
        output.WriteUInt32(IPTTL);
      }
      if (TCPFlags != 0) {
        output.WriteRawTag(208, 1);
        output.WriteUInt32(TCPFlags);
      }
      if (SrcMac != 0UL) {
        output.WriteRawTag(216, 1);
        output.WriteUInt64(SrcMac);
      }
      if (DstMac != 0UL) {
        output.WriteRawTag(224, 1);
        output.WriteUInt64(DstMac);
      }
      if (VlanId != 0) {
        output.WriteRawTag(232, 1);
        output.WriteUInt32(VlanId);
      }
      if (Etype != 0) {
        output.WriteRawTag(240, 1);
        output.WriteUInt32(Etype);
      }
      if (Direction != 0) {
        output.WriteRawTag(208, 5);
        output.WriteEnum((int) Direction);
      }
      if (Cid != 0) {
        output.WriteRawTag(216, 5);
        output.WriteUInt32(Cid);
      }
      if (Normalized != 0) {
        output.WriteRawTag(224, 5);
        output.WriteEnum((int) Normalized);
      }
      if (SrcIfName.Length != 0) {
        output.WriteRawTag(234, 5);
        output.WriteString(SrcIfName);
      }
      if (SrcIfDesc.Length != 0) {
        output.WriteRawTag(242, 5);
        output.WriteString(SrcIfDesc);
      }
      if (SrcIfSpeed != 0) {
        output.WriteRawTag(248, 5);
        output.WriteUInt32(SrcIfSpeed);
      }
      if (DstIfName.Length != 0) {
        output.WriteRawTag(130, 6);
        output.WriteString(DstIfName);
      }
      if (DstIfDesc.Length != 0) {
        output.WriteRawTag(138, 6);
        output.WriteString(DstIfDesc);
      }
      if (DstIfSpeed != 0) {
        output.WriteRawTag(144, 6);
        output.WriteUInt32(DstIfSpeed);
      }
      if (Peer.Length != 0) {
        output.WriteRawTag(154, 6);
        output.WriteString(Peer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (TimeRecvd != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimeRecvd);
      }
      if (SamplingRate != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SamplingRate);
      }
      if (SequenceNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SequenceNum);
      }
      if (TimeFlow != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimeFlow);
      }
      if (SrcIP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SrcIP);
      }
      if (DstIP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DstIP);
      }
      if (IPversion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) IPversion);
      }
      if (Bytes != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Bytes);
      }
      if (Packets != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Packets);
      }
      if (RouterAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RouterAddr);
      }
      if (NextHop.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(NextHop);
      }
      if (NextHopAS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NextHopAS);
      }
      if (SrcAS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SrcAS);
      }
      if (DstAS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DstAS);
      }
      if (SrcNet != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcNet);
      }
      if (DstNet != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstNet);
      }
      if (SrcIf != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcIf);
      }
      if (DstIf != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstIf);
      }
      if (Proto != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Proto);
      }
      if (SrcPort != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcPort);
      }
      if (DstPort != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstPort);
      }
      if (IPTos != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IPTos);
      }
      if (ForwardingStatus != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(ForwardingStatus);
      }
      if (IPTTL != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IPTTL);
      }
      if (TCPFlags != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(TCPFlags);
      }
      if (SrcMac != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(SrcMac);
      }
      if (DstMac != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(DstMac);
      }
      if (VlanId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(VlanId);
      }
      if (Etype != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Etype);
      }
      if (Direction != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Direction);
      }
      if (Cid != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Cid);
      }
      if (Normalized != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Normalized);
      }
      if (SrcIfName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SrcIfName);
      }
      if (SrcIfDesc.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SrcIfDesc);
      }
      if (SrcIfSpeed != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcIfSpeed);
      }
      if (DstIfName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(DstIfName);
      }
      if (DstIfDesc.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(DstIfDesc);
      }
      if (DstIfSpeed != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstIfSpeed);
      }
      if (Peer.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Peer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FlowMessage other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.TimeRecvd != 0UL) {
        TimeRecvd = other.TimeRecvd;
      }
      if (other.SamplingRate != 0UL) {
        SamplingRate = other.SamplingRate;
      }
      if (other.SequenceNum != 0) {
        SequenceNum = other.SequenceNum;
      }
      if (other.TimeFlow != 0UL) {
        TimeFlow = other.TimeFlow;
      }
      if (other.SrcIP.Length != 0) {
        SrcIP = other.SrcIP;
      }
      if (other.DstIP.Length != 0) {
        DstIP = other.DstIP;
      }
      if (other.IPversion != 0) {
        IPversion = other.IPversion;
      }
      if (other.Bytes != 0UL) {
        Bytes = other.Bytes;
      }
      if (other.Packets != 0UL) {
        Packets = other.Packets;
      }
      if (other.RouterAddr.Length != 0) {
        RouterAddr = other.RouterAddr;
      }
      if (other.NextHop.Length != 0) {
        NextHop = other.NextHop;
      }
      if (other.NextHopAS != 0) {
        NextHopAS = other.NextHopAS;
      }
      if (other.SrcAS != 0) {
        SrcAS = other.SrcAS;
      }
      if (other.DstAS != 0) {
        DstAS = other.DstAS;
      }
      if (other.SrcNet != 0) {
        SrcNet = other.SrcNet;
      }
      if (other.DstNet != 0) {
        DstNet = other.DstNet;
      }
      if (other.SrcIf != 0) {
        SrcIf = other.SrcIf;
      }
      if (other.DstIf != 0) {
        DstIf = other.DstIf;
      }
      if (other.Proto != 0) {
        Proto = other.Proto;
      }
      if (other.SrcPort != 0) {
        SrcPort = other.SrcPort;
      }
      if (other.DstPort != 0) {
        DstPort = other.DstPort;
      }
      if (other.IPTos != 0) {
        IPTos = other.IPTos;
      }
      if (other.ForwardingStatus != 0) {
        ForwardingStatus = other.ForwardingStatus;
      }
      if (other.IPTTL != 0) {
        IPTTL = other.IPTTL;
      }
      if (other.TCPFlags != 0) {
        TCPFlags = other.TCPFlags;
      }
      if (other.SrcMac != 0UL) {
        SrcMac = other.SrcMac;
      }
      if (other.DstMac != 0UL) {
        DstMac = other.DstMac;
      }
      if (other.VlanId != 0) {
        VlanId = other.VlanId;
      }
      if (other.Etype != 0) {
        Etype = other.Etype;
      }
      if (other.Direction != 0) {
        Direction = other.Direction;
      }
      if (other.Cid != 0) {
        Cid = other.Cid;
      }
      if (other.Normalized != 0) {
        Normalized = other.Normalized;
      }
      if (other.SrcIfName.Length != 0) {
        SrcIfName = other.SrcIfName;
      }
      if (other.SrcIfDesc.Length != 0) {
        SrcIfDesc = other.SrcIfDesc;
      }
      if (other.SrcIfSpeed != 0) {
        SrcIfSpeed = other.SrcIfSpeed;
      }
      if (other.DstIfName.Length != 0) {
        DstIfName = other.DstIfName;
      }
      if (other.DstIfDesc.Length != 0) {
        DstIfDesc = other.DstIfDesc;
      }
      if (other.DstIfSpeed != 0) {
        DstIfSpeed = other.DstIfSpeed;
      }
      if (other.Peer.Length != 0) {
        Peer = other.Peer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            type_ = (global::Flowmessageenriched.FlowMessage.Types.FlowType) input.ReadEnum();
            break;
          }
          case 16: {
            TimeRecvd = input.ReadUInt64();
            break;
          }
          case 24: {
            SamplingRate = input.ReadUInt64();
            break;
          }
          case 32: {
            SequenceNum = input.ReadUInt32();
            break;
          }
          case 40: {
            TimeFlow = input.ReadUInt64();
            break;
          }
          case 50: {
            SrcIP = input.ReadBytes();
            break;
          }
          case 58: {
            DstIP = input.ReadBytes();
            break;
          }
          case 64: {
            iPversion_ = (global::Flowmessageenriched.FlowMessage.Types.IPType) input.ReadEnum();
            break;
          }
          case 72: {
            Bytes = input.ReadUInt64();
            break;
          }
          case 80: {
            Packets = input.ReadUInt64();
            break;
          }
          case 90: {
            RouterAddr = input.ReadBytes();
            break;
          }
          case 98: {
            NextHop = input.ReadBytes();
            break;
          }
          case 104: {
            NextHopAS = input.ReadUInt32();
            break;
          }
          case 112: {
            SrcAS = input.ReadUInt32();
            break;
          }
          case 120: {
            DstAS = input.ReadUInt32();
            break;
          }
          case 128: {
            SrcNet = input.ReadUInt32();
            break;
          }
          case 136: {
            DstNet = input.ReadUInt32();
            break;
          }
          case 144: {
            SrcIf = input.ReadUInt32();
            break;
          }
          case 152: {
            DstIf = input.ReadUInt32();
            break;
          }
          case 160: {
            Proto = input.ReadUInt32();
            break;
          }
          case 168: {
            SrcPort = input.ReadUInt32();
            break;
          }
          case 176: {
            DstPort = input.ReadUInt32();
            break;
          }
          case 184: {
            IPTos = input.ReadUInt32();
            break;
          }
          case 192: {
            ForwardingStatus = input.ReadUInt32();
            break;
          }
          case 200: {
            IPTTL = input.ReadUInt32();
            break;
          }
          case 208: {
            TCPFlags = input.ReadUInt32();
            break;
          }
          case 216: {
            SrcMac = input.ReadUInt64();
            break;
          }
          case 224: {
            DstMac = input.ReadUInt64();
            break;
          }
          case 232: {
            VlanId = input.ReadUInt32();
            break;
          }
          case 240: {
            Etype = input.ReadUInt32();
            break;
          }
          case 720: {
            direction_ = (global::Flowmessageenriched.FlowMessage.Types.DirectionType) input.ReadEnum();
            break;
          }
          case 728: {
            Cid = input.ReadUInt32();
            break;
          }
          case 736: {
            normalized_ = (global::Flowmessageenriched.FlowMessage.Types.NormalizedType) input.ReadEnum();
            break;
          }
          case 746: {
            SrcIfName = input.ReadString();
            break;
          }
          case 754: {
            SrcIfDesc = input.ReadString();
            break;
          }
          case 760: {
            SrcIfSpeed = input.ReadUInt32();
            break;
          }
          case 770: {
            DstIfName = input.ReadString();
            break;
          }
          case 778: {
            DstIfDesc = input.ReadString();
            break;
          }
          case 784: {
            DstIfSpeed = input.ReadUInt32();
            break;
          }
          case 794: {
            Peer = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the FlowMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum FlowType {
        [pbr::OriginalName("FLOWUNKNOWN")] Flowunknown = 0,
        [pbr::OriginalName("NFV9")] Nfv9 = 9,
        [pbr::OriginalName("IPFIX")] Ipfix = 10,
        [pbr::OriginalName("SFLOW")] Sflow = 5,
      }

      /// <summary>
      /// To be deprecated
      /// </summary>
      public enum IPType {
        [pbr::OriginalName("IPUNKNOWN")] Ipunknown = 0,
        [pbr::OriginalName("IPv4")] Ipv4 = 4,
        [pbr::OriginalName("IPv6")] Ipv6 = 6,
      }

      /// <summary>
      /// Extensions beyond goflow's default protobuf, starting at id 90
      /// </summary>
      public enum DirectionType {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Incoming")] Incoming = 1,
        [pbr::OriginalName("Outgoing")] Outgoing = 2,
      }

      public enum NormalizedType {
        [pbr::OriginalName("No")] No = 0,
        [pbr::OriginalName("Yes")] Yes = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
