// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: flow-messages-enriched.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Flowmessageenriched {

  /// <summary>Holder for reflection information generated from flow-messages-enriched.proto</summary>
  public static partial class FlowMessagesEnrichedReflection {

    #region Descriptor
    /// <summary>File descriptor for flow-messages-enriched.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FlowMessagesEnrichedReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxmbG93LW1lc3NhZ2VzLWVucmljaGVkLnByb3RvEhNmbG93bWVzc2FnZWVu",
            "cmljaGVkIs8JCgtGbG93TWVzc2FnZRI3CgRUeXBlGAEgASgOMikuZmxvd21l",
            "c3NhZ2VlbnJpY2hlZC5GbG93TWVzc2FnZS5GbG93VHlwZRIUCgxUaW1lUmVj",
            "ZWl2ZWQYAiABKAQSEwoLU2VxdWVuY2VOdW0YBCABKA0SFAoMU2FtcGxpbmdS",
            "YXRlGAMgASgEEhUKDUZsb3dEaXJlY3Rpb24YKiABKA0SFgoOU2FtcGxlckFk",
            "ZHJlc3MYCyABKAwSFQoNVGltZUZsb3dTdGFydBgmIAEoBBITCgtUaW1lRmxv",
            "d0VuZBgFIAEoBBINCgVCeXRlcxgJIAEoBBIPCgdQYWNrZXRzGAogASgEEg8K",
            "B1NyY0FkZHIYBiABKAwSDwoHRHN0QWRkchgHIAEoDBINCgVFdHlwZRgeIAEo",
            "DRINCgVQcm90bxgUIAEoDRIPCgdTcmNQb3J0GBUgASgNEg8KB0RzdFBvcnQY",
            "FiABKA0SDQoFU3JjSWYYEiABKA0SDQoFRHN0SWYYEyABKA0SDgoGU3JjTWFj",
            "GBsgASgEEg4KBkRzdE1hYxgcIAEoBBIPCgdTcmNWbGFuGCEgASgNEg8KB0Rz",
            "dFZsYW4YIiABKA0SDgoGVmxhbklkGB0gASgNEhQKDEluZ3Jlc3NWcmZJRBgn",
            "IAEoDRITCgtFZ3Jlc3NWcmZJRBgoIAEoDRINCgVJUFRvcxgXIAEoDRIYChBG",
            "b3J3YXJkaW5nU3RhdHVzGBggASgNEg0KBUlQVFRMGBkgASgNEhAKCFRDUEZs",
            "YWdzGBogASgNEhAKCEljbXBUeXBlGB8gASgNEhAKCEljbXBDb2RlGCAgASgN",
            "EhUKDUlQdjZGbG93TGFiZWwYJSABKA0SHAoUSVB2NkV4dGVuc2lvbkhlYWRl",
            "cnMYKyABKA0SEgoKRnJhZ21lbnRJZBgjIAEoDRIWCg5GcmFnbWVudE9mZnNl",
            "dBgkIAEoDRIXCg9CaUZsb3dEaXJlY3Rpb24YKSABKA0SDQoFU3JjQVMYDiAB",
            "KA0SDQoFRHN0QVMYDyABKA0SDwoHTmV4dEhvcBgMIAEoDBIRCglOZXh0SG9w",
            "QVMYDSABKA0SDgoGU3JjTmV0GBAgASgNEg4KBkRzdE5ldBgRIAEoDRIMCgND",
            "aWQY6AcgASgNEhIKCUNpZFN0cmluZxjpByABKAkSRAoKTm9ybWFsaXplZBjq",
            "ByABKA4yLy5mbG93bWVzc2FnZWVucmljaGVkLkZsb3dNZXNzYWdlLk5vcm1h",
            "bGl6ZWRUeXBlEhIKCVNyY0lmTmFtZRjrByABKAkSEgoJU3JjSWZEZXNjGOwH",
            "IAEoCRITCgpTcmNJZlNwZWVkGO0HIAEoDRISCglEc3RJZk5hbWUY7gcgASgJ",
            "EhIKCURzdElmRGVzYxjvByABKAkSEwoKRHN0SWZTcGVlZBjwByABKA0SEgoJ",
            "UHJvdG9OYW1lGPEHIAEoCRIWCg1SZW1vdGVDb3VudHJ5GPIHIAEoCSJTCghG",
            "bG93VHlwZRIPCgtGTE9XVU5LTk9XThAAEgsKB1NGTE9XXzUQARIOCgpORVRG",
            "TE9XX1Y1EAISDgoKTkVURkxPV19WORADEgkKBUlQRklYEAQiIQoOTm9ybWFs",
            "aXplZFR5cGUSBgoCTm8QABIHCgNZZXMQAUIiCglid25ldGZsb3dCFUZsb3dN",
            "ZXNzYWdlRW5yaWNoZWRQYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Flowmessageenriched.FlowMessage), global::Flowmessageenriched.FlowMessage.Parser, new[]{ "Type", "TimeReceived", "SequenceNum", "SamplingRate", "FlowDirection", "SamplerAddress", "TimeFlowStart", "TimeFlowEnd", "Bytes", "Packets", "SrcAddr", "DstAddr", "Etype", "Proto", "SrcPort", "DstPort", "SrcIf", "DstIf", "SrcMac", "DstMac", "SrcVlan", "DstVlan", "VlanId", "IngressVrfID", "EgressVrfID", "IPTos", "ForwardingStatus", "IPTTL", "TCPFlags", "IcmpType", "IcmpCode", "IPv6FlowLabel", "IPv6ExtensionHeaders", "FragmentId", "FragmentOffset", "BiFlowDirection", "SrcAS", "DstAS", "NextHop", "NextHopAS", "SrcNet", "DstNet", "Cid", "CidString", "Normalized", "SrcIfName", "SrcIfDesc", "SrcIfSpeed", "DstIfName", "DstIfDesc", "DstIfSpeed", "ProtoName", "RemoteCountry" }, null, new[]{ typeof(global::Flowmessageenriched.FlowMessage.Types.FlowType), typeof(global::Flowmessageenriched.FlowMessage.Types.NormalizedType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FlowMessage : pb::IMessage<FlowMessage> {
    private static readonly pb::MessageParser<FlowMessage> _parser = new pb::MessageParser<FlowMessage>(() => new FlowMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FlowMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Flowmessageenriched.FlowMessagesEnrichedReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlowMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlowMessage(FlowMessage other) : this() {
      type_ = other.type_;
      timeReceived_ = other.timeReceived_;
      sequenceNum_ = other.sequenceNum_;
      samplingRate_ = other.samplingRate_;
      flowDirection_ = other.flowDirection_;
      samplerAddress_ = other.samplerAddress_;
      timeFlowStart_ = other.timeFlowStart_;
      timeFlowEnd_ = other.timeFlowEnd_;
      bytes_ = other.bytes_;
      packets_ = other.packets_;
      srcAddr_ = other.srcAddr_;
      dstAddr_ = other.dstAddr_;
      etype_ = other.etype_;
      proto_ = other.proto_;
      srcPort_ = other.srcPort_;
      dstPort_ = other.dstPort_;
      srcIf_ = other.srcIf_;
      dstIf_ = other.dstIf_;
      srcMac_ = other.srcMac_;
      dstMac_ = other.dstMac_;
      srcVlan_ = other.srcVlan_;
      dstVlan_ = other.dstVlan_;
      vlanId_ = other.vlanId_;
      ingressVrfID_ = other.ingressVrfID_;
      egressVrfID_ = other.egressVrfID_;
      iPTos_ = other.iPTos_;
      forwardingStatus_ = other.forwardingStatus_;
      iPTTL_ = other.iPTTL_;
      tCPFlags_ = other.tCPFlags_;
      icmpType_ = other.icmpType_;
      icmpCode_ = other.icmpCode_;
      iPv6FlowLabel_ = other.iPv6FlowLabel_;
      iPv6ExtensionHeaders_ = other.iPv6ExtensionHeaders_;
      fragmentId_ = other.fragmentId_;
      fragmentOffset_ = other.fragmentOffset_;
      biFlowDirection_ = other.biFlowDirection_;
      srcAS_ = other.srcAS_;
      dstAS_ = other.dstAS_;
      nextHop_ = other.nextHop_;
      nextHopAS_ = other.nextHopAS_;
      srcNet_ = other.srcNet_;
      dstNet_ = other.dstNet_;
      cid_ = other.cid_;
      cidString_ = other.cidString_;
      normalized_ = other.normalized_;
      srcIfName_ = other.srcIfName_;
      srcIfDesc_ = other.srcIfDesc_;
      srcIfSpeed_ = other.srcIfSpeed_;
      dstIfName_ = other.dstIfName_;
      dstIfDesc_ = other.dstIfDesc_;
      dstIfSpeed_ = other.dstIfSpeed_;
      protoName_ = other.protoName_;
      remoteCountry_ = other.remoteCountry_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FlowMessage Clone() {
      return new FlowMessage(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Flowmessageenriched.FlowMessage.Types.FlowType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Flowmessageenriched.FlowMessage.Types.FlowType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "TimeReceived" field.</summary>
    public const int TimeReceivedFieldNumber = 2;
    private ulong timeReceived_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong TimeReceived {
      get { return timeReceived_; }
      set {
        timeReceived_ = value;
      }
    }

    /// <summary>Field number for the "SequenceNum" field.</summary>
    public const int SequenceNumFieldNumber = 4;
    private uint sequenceNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SequenceNum {
      get { return sequenceNum_; }
      set {
        sequenceNum_ = value;
      }
    }

    /// <summary>Field number for the "SamplingRate" field.</summary>
    public const int SamplingRateFieldNumber = 3;
    private ulong samplingRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong SamplingRate {
      get { return samplingRate_; }
      set {
        samplingRate_ = value;
      }
    }

    /// <summary>Field number for the "FlowDirection" field.</summary>
    public const int FlowDirectionFieldNumber = 42;
    private uint flowDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint FlowDirection {
      get { return flowDirection_; }
      set {
        flowDirection_ = value;
      }
    }

    /// <summary>Field number for the "SamplerAddress" field.</summary>
    public const int SamplerAddressFieldNumber = 11;
    private pb::ByteString samplerAddress_ = pb::ByteString.Empty;
    /// <summary>
    /// Sampler information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SamplerAddress {
      get { return samplerAddress_; }
      set {
        samplerAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TimeFlowStart" field.</summary>
    public const int TimeFlowStartFieldNumber = 38;
    private ulong timeFlowStart_;
    /// <summary>
    /// Found inside packet
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong TimeFlowStart {
      get { return timeFlowStart_; }
      set {
        timeFlowStart_ = value;
      }
    }

    /// <summary>Field number for the "TimeFlowEnd" field.</summary>
    public const int TimeFlowEndFieldNumber = 5;
    private ulong timeFlowEnd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong TimeFlowEnd {
      get { return timeFlowEnd_; }
      set {
        timeFlowEnd_ = value;
      }
    }

    /// <summary>Field number for the "Bytes" field.</summary>
    public const int BytesFieldNumber = 9;
    private ulong bytes_;
    /// <summary>
    /// Size of the sampled packet
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Bytes {
      get { return bytes_; }
      set {
        bytes_ = value;
      }
    }

    /// <summary>Field number for the "Packets" field.</summary>
    public const int PacketsFieldNumber = 10;
    private ulong packets_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Packets {
      get { return packets_; }
      set {
        packets_ = value;
      }
    }

    /// <summary>Field number for the "SrcAddr" field.</summary>
    public const int SrcAddrFieldNumber = 6;
    private pb::ByteString srcAddr_ = pb::ByteString.Empty;
    /// <summary>
    /// Source/destination addresses
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString SrcAddr {
      get { return srcAddr_; }
      set {
        srcAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DstAddr" field.</summary>
    public const int DstAddrFieldNumber = 7;
    private pb::ByteString dstAddr_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString DstAddr {
      get { return dstAddr_; }
      set {
        dstAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Etype" field.</summary>
    public const int EtypeFieldNumber = 30;
    private uint etype_;
    /// <summary>
    /// Layer 3 protocol (IPv4/IPv6/ARP/...)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Etype {
      get { return etype_; }
      set {
        etype_ = value;
      }
    }

    /// <summary>Field number for the "Proto" field.</summary>
    public const int ProtoFieldNumber = 20;
    private uint proto_;
    /// <summary>
    /// Layer 4 protocol
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Proto {
      get { return proto_; }
      set {
        proto_ = value;
      }
    }

    /// <summary>Field number for the "SrcPort" field.</summary>
    public const int SrcPortFieldNumber = 21;
    private uint srcPort_;
    /// <summary>
    /// Ports for UDP and TCP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcPort {
      get { return srcPort_; }
      set {
        srcPort_ = value;
      }
    }

    /// <summary>Field number for the "DstPort" field.</summary>
    public const int DstPortFieldNumber = 22;
    private uint dstPort_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstPort {
      get { return dstPort_; }
      set {
        dstPort_ = value;
      }
    }

    /// <summary>Field number for the "SrcIf" field.</summary>
    public const int SrcIfFieldNumber = 18;
    private uint srcIf_;
    /// <summary>
    /// Interfaces
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcIf {
      get { return srcIf_; }
      set {
        srcIf_ = value;
      }
    }

    /// <summary>Field number for the "DstIf" field.</summary>
    public const int DstIfFieldNumber = 19;
    private uint dstIf_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstIf {
      get { return dstIf_; }
      set {
        dstIf_ = value;
      }
    }

    /// <summary>Field number for the "SrcMac" field.</summary>
    public const int SrcMacFieldNumber = 27;
    private ulong srcMac_;
    /// <summary>
    /// Ethernet information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong SrcMac {
      get { return srcMac_; }
      set {
        srcMac_ = value;
      }
    }

    /// <summary>Field number for the "DstMac" field.</summary>
    public const int DstMacFieldNumber = 28;
    private ulong dstMac_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong DstMac {
      get { return dstMac_; }
      set {
        dstMac_ = value;
      }
    }

    /// <summary>Field number for the "SrcVlan" field.</summary>
    public const int SrcVlanFieldNumber = 33;
    private uint srcVlan_;
    /// <summary>
    /// Vlan
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcVlan {
      get { return srcVlan_; }
      set {
        srcVlan_ = value;
      }
    }

    /// <summary>Field number for the "DstVlan" field.</summary>
    public const int DstVlanFieldNumber = 34;
    private uint dstVlan_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstVlan {
      get { return dstVlan_; }
      set {
        dstVlan_ = value;
      }
    }

    /// <summary>Field number for the "VlanId" field.</summary>
    public const int VlanIdFieldNumber = 29;
    private uint vlanId_;
    /// <summary>
    /// 802.1q VLAN in sampled packet
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint VlanId {
      get { return vlanId_; }
      set {
        vlanId_ = value;
      }
    }

    /// <summary>Field number for the "IngressVrfID" field.</summary>
    public const int IngressVrfIDFieldNumber = 39;
    private uint ingressVrfID_;
    /// <summary>
    /// VRF
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IngressVrfID {
      get { return ingressVrfID_; }
      set {
        ingressVrfID_ = value;
      }
    }

    /// <summary>Field number for the "EgressVrfID" field.</summary>
    public const int EgressVrfIDFieldNumber = 40;
    private uint egressVrfID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint EgressVrfID {
      get { return egressVrfID_; }
      set {
        egressVrfID_ = value;
      }
    }

    /// <summary>Field number for the "IPTos" field.</summary>
    public const int IPTosFieldNumber = 23;
    private uint iPTos_;
    /// <summary>
    /// IP and TCP special flags
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IPTos {
      get { return iPTos_; }
      set {
        iPTos_ = value;
      }
    }

    /// <summary>Field number for the "ForwardingStatus" field.</summary>
    public const int ForwardingStatusFieldNumber = 24;
    private uint forwardingStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ForwardingStatus {
      get { return forwardingStatus_; }
      set {
        forwardingStatus_ = value;
      }
    }

    /// <summary>Field number for the "IPTTL" field.</summary>
    public const int IPTTLFieldNumber = 25;
    private uint iPTTL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IPTTL {
      get { return iPTTL_; }
      set {
        iPTTL_ = value;
      }
    }

    /// <summary>Field number for the "TCPFlags" field.</summary>
    public const int TCPFlagsFieldNumber = 26;
    private uint tCPFlags_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint TCPFlags {
      get { return tCPFlags_; }
      set {
        tCPFlags_ = value;
      }
    }

    /// <summary>Field number for the "IcmpType" field.</summary>
    public const int IcmpTypeFieldNumber = 31;
    private uint icmpType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IcmpType {
      get { return icmpType_; }
      set {
        icmpType_ = value;
      }
    }

    /// <summary>Field number for the "IcmpCode" field.</summary>
    public const int IcmpCodeFieldNumber = 32;
    private uint icmpCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IcmpCode {
      get { return icmpCode_; }
      set {
        icmpCode_ = value;
      }
    }

    /// <summary>Field number for the "IPv6FlowLabel" field.</summary>
    public const int IPv6FlowLabelFieldNumber = 37;
    private uint iPv6FlowLabel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IPv6FlowLabel {
      get { return iPv6FlowLabel_; }
      set {
        iPv6FlowLabel_ = value;
      }
    }

    /// <summary>Field number for the "IPv6ExtensionHeaders" field.</summary>
    public const int IPv6ExtensionHeadersFieldNumber = 43;
    private uint iPv6ExtensionHeaders_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint IPv6ExtensionHeaders {
      get { return iPv6ExtensionHeaders_; }
      set {
        iPv6ExtensionHeaders_ = value;
      }
    }

    /// <summary>Field number for the "FragmentId" field.</summary>
    public const int FragmentIdFieldNumber = 35;
    private uint fragmentId_;
    /// <summary>
    /// Fragments (IPv4/IPv6)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint FragmentId {
      get { return fragmentId_; }
      set {
        fragmentId_ = value;
      }
    }

    /// <summary>Field number for the "FragmentOffset" field.</summary>
    public const int FragmentOffsetFieldNumber = 36;
    private uint fragmentOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint FragmentOffset {
      get { return fragmentOffset_; }
      set {
        fragmentOffset_ = value;
      }
    }

    /// <summary>Field number for the "BiFlowDirection" field.</summary>
    public const int BiFlowDirectionFieldNumber = 41;
    private uint biFlowDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint BiFlowDirection {
      get { return biFlowDirection_; }
      set {
        biFlowDirection_ = value;
      }
    }

    /// <summary>Field number for the "SrcAS" field.</summary>
    public const int SrcASFieldNumber = 14;
    private uint srcAS_;
    /// <summary>
    /// Autonomous system information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcAS {
      get { return srcAS_; }
      set {
        srcAS_ = value;
      }
    }

    /// <summary>Field number for the "DstAS" field.</summary>
    public const int DstASFieldNumber = 15;
    private uint dstAS_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstAS {
      get { return dstAS_; }
      set {
        dstAS_ = value;
      }
    }

    /// <summary>Field number for the "NextHop" field.</summary>
    public const int NextHopFieldNumber = 12;
    private pb::ByteString nextHop_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString NextHop {
      get { return nextHop_; }
      set {
        nextHop_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "NextHopAS" field.</summary>
    public const int NextHopASFieldNumber = 13;
    private uint nextHopAS_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint NextHopAS {
      get { return nextHopAS_; }
      set {
        nextHopAS_ = value;
      }
    }

    /// <summary>Field number for the "SrcNet" field.</summary>
    public const int SrcNetFieldNumber = 16;
    private uint srcNet_;
    /// <summary>
    /// Prefix size
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcNet {
      get { return srcNet_; }
      set {
        srcNet_ = value;
      }
    }

    /// <summary>Field number for the "DstNet" field.</summary>
    public const int DstNetFieldNumber = 17;
    private uint dstNet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstNet {
      get { return dstNet_; }
      set {
        dstNet_ = value;
      }
    }

    /// <summary>Field number for the "Cid" field.</summary>
    public const int CidFieldNumber = 1000;
    private uint cid_;
    /// <summary>
    /// bwNetFlow enricher fields
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Cid {
      get { return cid_; }
      set {
        cid_ = value;
      }
    }

    /// <summary>Field number for the "CidString" field.</summary>
    public const int CidStringFieldNumber = 1001;
    private string cidString_ = "";
    /// <summary>
    /// Customer ID - a more generalized ID, assigned by prefix
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CidString {
      get { return cidString_; }
      set {
        cidString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Normalized" field.</summary>
    public const int NormalizedFieldNumber = 1002;
    private global::Flowmessageenriched.FlowMessage.Types.NormalizedType normalized_ = 0;
    /// <summary>
    /// Normalization - whether the sampling rate is accounted for
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Flowmessageenriched.FlowMessage.Types.NormalizedType Normalized {
      get { return normalized_; }
      set {
        normalized_ = value;
      }
    }

    /// <summary>Field number for the "SrcIfName" field.</summary>
    public const int SrcIfNameFieldNumber = 1003;
    private string srcIfName_ = "";
    /// <summary>
    /// Fields for Interface Usability -- enriched using SNMP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SrcIfName {
      get { return srcIfName_; }
      set {
        srcIfName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SrcIfDesc" field.</summary>
    public const int SrcIfDescFieldNumber = 1004;
    private string srcIfDesc_ = "";
    /// <summary>
    /// set to the descrition, filtered by a regex in the enricher
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SrcIfDesc {
      get { return srcIfDesc_; }
      set {
        srcIfDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SrcIfSpeed" field.</summary>
    public const int SrcIfSpeedFieldNumber = 1005;
    private uint srcIfSpeed_;
    /// <summary>
    /// iface speed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint SrcIfSpeed {
      get { return srcIfSpeed_; }
      set {
        srcIfSpeed_ = value;
      }
    }

    /// <summary>Field number for the "DstIfName" field.</summary>
    public const int DstIfNameFieldNumber = 1006;
    private string dstIfName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DstIfName {
      get { return dstIfName_; }
      set {
        dstIfName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DstIfDesc" field.</summary>
    public const int DstIfDescFieldNumber = 1007;
    private string dstIfDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DstIfDesc {
      get { return dstIfDesc_; }
      set {
        dstIfDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DstIfSpeed" field.</summary>
    public const int DstIfSpeedFieldNumber = 1008;
    private uint dstIfSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint DstIfSpeed {
      get { return dstIfSpeed_; }
      set {
        dstIfSpeed_ = value;
      }
    }

    /// <summary>Field number for the "ProtoName" field.</summary>
    public const int ProtoNameFieldNumber = 1009;
    private string protoName_ = "";
    /// <summary>
    /// Protocol Name -- set for some well known protocols, based on Proto
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProtoName {
      get { return protoName_; }
      set {
        protoName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "RemoteCountry" field.</summary>
    public const int RemoteCountryFieldNumber = 1010;
    private string remoteCountry_ = "";
    /// <summary>
    /// Geolocation -- set using the provided database
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RemoteCountry {
      get { return remoteCountry_; }
      set {
        remoteCountry_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FlowMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FlowMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (TimeReceived != other.TimeReceived) return false;
      if (SequenceNum != other.SequenceNum) return false;
      if (SamplingRate != other.SamplingRate) return false;
      if (FlowDirection != other.FlowDirection) return false;
      if (SamplerAddress != other.SamplerAddress) return false;
      if (TimeFlowStart != other.TimeFlowStart) return false;
      if (TimeFlowEnd != other.TimeFlowEnd) return false;
      if (Bytes != other.Bytes) return false;
      if (Packets != other.Packets) return false;
      if (SrcAddr != other.SrcAddr) return false;
      if (DstAddr != other.DstAddr) return false;
      if (Etype != other.Etype) return false;
      if (Proto != other.Proto) return false;
      if (SrcPort != other.SrcPort) return false;
      if (DstPort != other.DstPort) return false;
      if (SrcIf != other.SrcIf) return false;
      if (DstIf != other.DstIf) return false;
      if (SrcMac != other.SrcMac) return false;
      if (DstMac != other.DstMac) return false;
      if (SrcVlan != other.SrcVlan) return false;
      if (DstVlan != other.DstVlan) return false;
      if (VlanId != other.VlanId) return false;
      if (IngressVrfID != other.IngressVrfID) return false;
      if (EgressVrfID != other.EgressVrfID) return false;
      if (IPTos != other.IPTos) return false;
      if (ForwardingStatus != other.ForwardingStatus) return false;
      if (IPTTL != other.IPTTL) return false;
      if (TCPFlags != other.TCPFlags) return false;
      if (IcmpType != other.IcmpType) return false;
      if (IcmpCode != other.IcmpCode) return false;
      if (IPv6FlowLabel != other.IPv6FlowLabel) return false;
      if (IPv6ExtensionHeaders != other.IPv6ExtensionHeaders) return false;
      if (FragmentId != other.FragmentId) return false;
      if (FragmentOffset != other.FragmentOffset) return false;
      if (BiFlowDirection != other.BiFlowDirection) return false;
      if (SrcAS != other.SrcAS) return false;
      if (DstAS != other.DstAS) return false;
      if (NextHop != other.NextHop) return false;
      if (NextHopAS != other.NextHopAS) return false;
      if (SrcNet != other.SrcNet) return false;
      if (DstNet != other.DstNet) return false;
      if (Cid != other.Cid) return false;
      if (CidString != other.CidString) return false;
      if (Normalized != other.Normalized) return false;
      if (SrcIfName != other.SrcIfName) return false;
      if (SrcIfDesc != other.SrcIfDesc) return false;
      if (SrcIfSpeed != other.SrcIfSpeed) return false;
      if (DstIfName != other.DstIfName) return false;
      if (DstIfDesc != other.DstIfDesc) return false;
      if (DstIfSpeed != other.DstIfSpeed) return false;
      if (ProtoName != other.ProtoName) return false;
      if (RemoteCountry != other.RemoteCountry) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (TimeReceived != 0UL) hash ^= TimeReceived.GetHashCode();
      if (SequenceNum != 0) hash ^= SequenceNum.GetHashCode();
      if (SamplingRate != 0UL) hash ^= SamplingRate.GetHashCode();
      if (FlowDirection != 0) hash ^= FlowDirection.GetHashCode();
      if (SamplerAddress.Length != 0) hash ^= SamplerAddress.GetHashCode();
      if (TimeFlowStart != 0UL) hash ^= TimeFlowStart.GetHashCode();
      if (TimeFlowEnd != 0UL) hash ^= TimeFlowEnd.GetHashCode();
      if (Bytes != 0UL) hash ^= Bytes.GetHashCode();
      if (Packets != 0UL) hash ^= Packets.GetHashCode();
      if (SrcAddr.Length != 0) hash ^= SrcAddr.GetHashCode();
      if (DstAddr.Length != 0) hash ^= DstAddr.GetHashCode();
      if (Etype != 0) hash ^= Etype.GetHashCode();
      if (Proto != 0) hash ^= Proto.GetHashCode();
      if (SrcPort != 0) hash ^= SrcPort.GetHashCode();
      if (DstPort != 0) hash ^= DstPort.GetHashCode();
      if (SrcIf != 0) hash ^= SrcIf.GetHashCode();
      if (DstIf != 0) hash ^= DstIf.GetHashCode();
      if (SrcMac != 0UL) hash ^= SrcMac.GetHashCode();
      if (DstMac != 0UL) hash ^= DstMac.GetHashCode();
      if (SrcVlan != 0) hash ^= SrcVlan.GetHashCode();
      if (DstVlan != 0) hash ^= DstVlan.GetHashCode();
      if (VlanId != 0) hash ^= VlanId.GetHashCode();
      if (IngressVrfID != 0) hash ^= IngressVrfID.GetHashCode();
      if (EgressVrfID != 0) hash ^= EgressVrfID.GetHashCode();
      if (IPTos != 0) hash ^= IPTos.GetHashCode();
      if (ForwardingStatus != 0) hash ^= ForwardingStatus.GetHashCode();
      if (IPTTL != 0) hash ^= IPTTL.GetHashCode();
      if (TCPFlags != 0) hash ^= TCPFlags.GetHashCode();
      if (IcmpType != 0) hash ^= IcmpType.GetHashCode();
      if (IcmpCode != 0) hash ^= IcmpCode.GetHashCode();
      if (IPv6FlowLabel != 0) hash ^= IPv6FlowLabel.GetHashCode();
      if (IPv6ExtensionHeaders != 0) hash ^= IPv6ExtensionHeaders.GetHashCode();
      if (FragmentId != 0) hash ^= FragmentId.GetHashCode();
      if (FragmentOffset != 0) hash ^= FragmentOffset.GetHashCode();
      if (BiFlowDirection != 0) hash ^= BiFlowDirection.GetHashCode();
      if (SrcAS != 0) hash ^= SrcAS.GetHashCode();
      if (DstAS != 0) hash ^= DstAS.GetHashCode();
      if (NextHop.Length != 0) hash ^= NextHop.GetHashCode();
      if (NextHopAS != 0) hash ^= NextHopAS.GetHashCode();
      if (SrcNet != 0) hash ^= SrcNet.GetHashCode();
      if (DstNet != 0) hash ^= DstNet.GetHashCode();
      if (Cid != 0) hash ^= Cid.GetHashCode();
      if (CidString.Length != 0) hash ^= CidString.GetHashCode();
      if (Normalized != 0) hash ^= Normalized.GetHashCode();
      if (SrcIfName.Length != 0) hash ^= SrcIfName.GetHashCode();
      if (SrcIfDesc.Length != 0) hash ^= SrcIfDesc.GetHashCode();
      if (SrcIfSpeed != 0) hash ^= SrcIfSpeed.GetHashCode();
      if (DstIfName.Length != 0) hash ^= DstIfName.GetHashCode();
      if (DstIfDesc.Length != 0) hash ^= DstIfDesc.GetHashCode();
      if (DstIfSpeed != 0) hash ^= DstIfSpeed.GetHashCode();
      if (ProtoName.Length != 0) hash ^= ProtoName.GetHashCode();
      if (RemoteCountry.Length != 0) hash ^= RemoteCountry.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (TimeReceived != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(TimeReceived);
      }
      if (SamplingRate != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(SamplingRate);
      }
      if (SequenceNum != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(SequenceNum);
      }
      if (TimeFlowEnd != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(TimeFlowEnd);
      }
      if (SrcAddr.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(SrcAddr);
      }
      if (DstAddr.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(DstAddr);
      }
      if (Bytes != 0UL) {
        output.WriteRawTag(72);
        output.WriteUInt64(Bytes);
      }
      if (Packets != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(Packets);
      }
      if (SamplerAddress.Length != 0) {
        output.WriteRawTag(90);
        output.WriteBytes(SamplerAddress);
      }
      if (NextHop.Length != 0) {
        output.WriteRawTag(98);
        output.WriteBytes(NextHop);
      }
      if (NextHopAS != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(NextHopAS);
      }
      if (SrcAS != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(SrcAS);
      }
      if (DstAS != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(DstAS);
      }
      if (SrcNet != 0) {
        output.WriteRawTag(128, 1);
        output.WriteUInt32(SrcNet);
      }
      if (DstNet != 0) {
        output.WriteRawTag(136, 1);
        output.WriteUInt32(DstNet);
      }
      if (SrcIf != 0) {
        output.WriteRawTag(144, 1);
        output.WriteUInt32(SrcIf);
      }
      if (DstIf != 0) {
        output.WriteRawTag(152, 1);
        output.WriteUInt32(DstIf);
      }
      if (Proto != 0) {
        output.WriteRawTag(160, 1);
        output.WriteUInt32(Proto);
      }
      if (SrcPort != 0) {
        output.WriteRawTag(168, 1);
        output.WriteUInt32(SrcPort);
      }
      if (DstPort != 0) {
        output.WriteRawTag(176, 1);
        output.WriteUInt32(DstPort);
      }
      if (IPTos != 0) {
        output.WriteRawTag(184, 1);
        output.WriteUInt32(IPTos);
      }
      if (ForwardingStatus != 0) {
        output.WriteRawTag(192, 1);
        output.WriteUInt32(ForwardingStatus);
      }
      if (IPTTL != 0) {
        output.WriteRawTag(200, 1);
        output.WriteUInt32(IPTTL);
      }
      if (TCPFlags != 0) {
        output.WriteRawTag(208, 1);
        output.WriteUInt32(TCPFlags);
      }
      if (SrcMac != 0UL) {
        output.WriteRawTag(216, 1);
        output.WriteUInt64(SrcMac);
      }
      if (DstMac != 0UL) {
        output.WriteRawTag(224, 1);
        output.WriteUInt64(DstMac);
      }
      if (VlanId != 0) {
        output.WriteRawTag(232, 1);
        output.WriteUInt32(VlanId);
      }
      if (Etype != 0) {
        output.WriteRawTag(240, 1);
        output.WriteUInt32(Etype);
      }
      if (IcmpType != 0) {
        output.WriteRawTag(248, 1);
        output.WriteUInt32(IcmpType);
      }
      if (IcmpCode != 0) {
        output.WriteRawTag(128, 2);
        output.WriteUInt32(IcmpCode);
      }
      if (SrcVlan != 0) {
        output.WriteRawTag(136, 2);
        output.WriteUInt32(SrcVlan);
      }
      if (DstVlan != 0) {
        output.WriteRawTag(144, 2);
        output.WriteUInt32(DstVlan);
      }
      if (FragmentId != 0) {
        output.WriteRawTag(152, 2);
        output.WriteUInt32(FragmentId);
      }
      if (FragmentOffset != 0) {
        output.WriteRawTag(160, 2);
        output.WriteUInt32(FragmentOffset);
      }
      if (IPv6FlowLabel != 0) {
        output.WriteRawTag(168, 2);
        output.WriteUInt32(IPv6FlowLabel);
      }
      if (TimeFlowStart != 0UL) {
        output.WriteRawTag(176, 2);
        output.WriteUInt64(TimeFlowStart);
      }
      if (IngressVrfID != 0) {
        output.WriteRawTag(184, 2);
        output.WriteUInt32(IngressVrfID);
      }
      if (EgressVrfID != 0) {
        output.WriteRawTag(192, 2);
        output.WriteUInt32(EgressVrfID);
      }
      if (BiFlowDirection != 0) {
        output.WriteRawTag(200, 2);
        output.WriteUInt32(BiFlowDirection);
      }
      if (FlowDirection != 0) {
        output.WriteRawTag(208, 2);
        output.WriteUInt32(FlowDirection);
      }
      if (IPv6ExtensionHeaders != 0) {
        output.WriteRawTag(216, 2);
        output.WriteUInt32(IPv6ExtensionHeaders);
      }
      if (Cid != 0) {
        output.WriteRawTag(192, 62);
        output.WriteUInt32(Cid);
      }
      if (CidString.Length != 0) {
        output.WriteRawTag(202, 62);
        output.WriteString(CidString);
      }
      if (Normalized != 0) {
        output.WriteRawTag(208, 62);
        output.WriteEnum((int) Normalized);
      }
      if (SrcIfName.Length != 0) {
        output.WriteRawTag(218, 62);
        output.WriteString(SrcIfName);
      }
      if (SrcIfDesc.Length != 0) {
        output.WriteRawTag(226, 62);
        output.WriteString(SrcIfDesc);
      }
      if (SrcIfSpeed != 0) {
        output.WriteRawTag(232, 62);
        output.WriteUInt32(SrcIfSpeed);
      }
      if (DstIfName.Length != 0) {
        output.WriteRawTag(242, 62);
        output.WriteString(DstIfName);
      }
      if (DstIfDesc.Length != 0) {
        output.WriteRawTag(250, 62);
        output.WriteString(DstIfDesc);
      }
      if (DstIfSpeed != 0) {
        output.WriteRawTag(128, 63);
        output.WriteUInt32(DstIfSpeed);
      }
      if (ProtoName.Length != 0) {
        output.WriteRawTag(138, 63);
        output.WriteString(ProtoName);
      }
      if (RemoteCountry.Length != 0) {
        output.WriteRawTag(146, 63);
        output.WriteString(RemoteCountry);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (TimeReceived != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimeReceived);
      }
      if (SequenceNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SequenceNum);
      }
      if (SamplingRate != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SamplingRate);
      }
      if (FlowDirection != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(FlowDirection);
      }
      if (SamplerAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SamplerAddress);
      }
      if (TimeFlowStart != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(TimeFlowStart);
      }
      if (TimeFlowEnd != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimeFlowEnd);
      }
      if (Bytes != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Bytes);
      }
      if (Packets != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Packets);
      }
      if (SrcAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(SrcAddr);
      }
      if (DstAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DstAddr);
      }
      if (Etype != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Etype);
      }
      if (Proto != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Proto);
      }
      if (SrcPort != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcPort);
      }
      if (DstPort != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstPort);
      }
      if (SrcIf != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcIf);
      }
      if (DstIf != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstIf);
      }
      if (SrcMac != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(SrcMac);
      }
      if (DstMac != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(DstMac);
      }
      if (SrcVlan != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcVlan);
      }
      if (DstVlan != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstVlan);
      }
      if (VlanId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(VlanId);
      }
      if (IngressVrfID != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IngressVrfID);
      }
      if (EgressVrfID != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(EgressVrfID);
      }
      if (IPTos != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IPTos);
      }
      if (ForwardingStatus != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(ForwardingStatus);
      }
      if (IPTTL != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IPTTL);
      }
      if (TCPFlags != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(TCPFlags);
      }
      if (IcmpType != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IcmpType);
      }
      if (IcmpCode != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IcmpCode);
      }
      if (IPv6FlowLabel != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IPv6FlowLabel);
      }
      if (IPv6ExtensionHeaders != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IPv6ExtensionHeaders);
      }
      if (FragmentId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(FragmentId);
      }
      if (FragmentOffset != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(FragmentOffset);
      }
      if (BiFlowDirection != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(BiFlowDirection);
      }
      if (SrcAS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SrcAS);
      }
      if (DstAS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DstAS);
      }
      if (NextHop.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(NextHop);
      }
      if (NextHopAS != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NextHopAS);
      }
      if (SrcNet != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcNet);
      }
      if (DstNet != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstNet);
      }
      if (Cid != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Cid);
      }
      if (CidString.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(CidString);
      }
      if (Normalized != 0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Normalized);
      }
      if (SrcIfName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SrcIfName);
      }
      if (SrcIfDesc.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SrcIfDesc);
      }
      if (SrcIfSpeed != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SrcIfSpeed);
      }
      if (DstIfName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(DstIfName);
      }
      if (DstIfDesc.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(DstIfDesc);
      }
      if (DstIfSpeed != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DstIfSpeed);
      }
      if (ProtoName.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ProtoName);
      }
      if (RemoteCountry.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(RemoteCountry);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FlowMessage other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.TimeReceived != 0UL) {
        TimeReceived = other.TimeReceived;
      }
      if (other.SequenceNum != 0) {
        SequenceNum = other.SequenceNum;
      }
      if (other.SamplingRate != 0UL) {
        SamplingRate = other.SamplingRate;
      }
      if (other.FlowDirection != 0) {
        FlowDirection = other.FlowDirection;
      }
      if (other.SamplerAddress.Length != 0) {
        SamplerAddress = other.SamplerAddress;
      }
      if (other.TimeFlowStart != 0UL) {
        TimeFlowStart = other.TimeFlowStart;
      }
      if (other.TimeFlowEnd != 0UL) {
        TimeFlowEnd = other.TimeFlowEnd;
      }
      if (other.Bytes != 0UL) {
        Bytes = other.Bytes;
      }
      if (other.Packets != 0UL) {
        Packets = other.Packets;
      }
      if (other.SrcAddr.Length != 0) {
        SrcAddr = other.SrcAddr;
      }
      if (other.DstAddr.Length != 0) {
        DstAddr = other.DstAddr;
      }
      if (other.Etype != 0) {
        Etype = other.Etype;
      }
      if (other.Proto != 0) {
        Proto = other.Proto;
      }
      if (other.SrcPort != 0) {
        SrcPort = other.SrcPort;
      }
      if (other.DstPort != 0) {
        DstPort = other.DstPort;
      }
      if (other.SrcIf != 0) {
        SrcIf = other.SrcIf;
      }
      if (other.DstIf != 0) {
        DstIf = other.DstIf;
      }
      if (other.SrcMac != 0UL) {
        SrcMac = other.SrcMac;
      }
      if (other.DstMac != 0UL) {
        DstMac = other.DstMac;
      }
      if (other.SrcVlan != 0) {
        SrcVlan = other.SrcVlan;
      }
      if (other.DstVlan != 0) {
        DstVlan = other.DstVlan;
      }
      if (other.VlanId != 0) {
        VlanId = other.VlanId;
      }
      if (other.IngressVrfID != 0) {
        IngressVrfID = other.IngressVrfID;
      }
      if (other.EgressVrfID != 0) {
        EgressVrfID = other.EgressVrfID;
      }
      if (other.IPTos != 0) {
        IPTos = other.IPTos;
      }
      if (other.ForwardingStatus != 0) {
        ForwardingStatus = other.ForwardingStatus;
      }
      if (other.IPTTL != 0) {
        IPTTL = other.IPTTL;
      }
      if (other.TCPFlags != 0) {
        TCPFlags = other.TCPFlags;
      }
      if (other.IcmpType != 0) {
        IcmpType = other.IcmpType;
      }
      if (other.IcmpCode != 0) {
        IcmpCode = other.IcmpCode;
      }
      if (other.IPv6FlowLabel != 0) {
        IPv6FlowLabel = other.IPv6FlowLabel;
      }
      if (other.IPv6ExtensionHeaders != 0) {
        IPv6ExtensionHeaders = other.IPv6ExtensionHeaders;
      }
      if (other.FragmentId != 0) {
        FragmentId = other.FragmentId;
      }
      if (other.FragmentOffset != 0) {
        FragmentOffset = other.FragmentOffset;
      }
      if (other.BiFlowDirection != 0) {
        BiFlowDirection = other.BiFlowDirection;
      }
      if (other.SrcAS != 0) {
        SrcAS = other.SrcAS;
      }
      if (other.DstAS != 0) {
        DstAS = other.DstAS;
      }
      if (other.NextHop.Length != 0) {
        NextHop = other.NextHop;
      }
      if (other.NextHopAS != 0) {
        NextHopAS = other.NextHopAS;
      }
      if (other.SrcNet != 0) {
        SrcNet = other.SrcNet;
      }
      if (other.DstNet != 0) {
        DstNet = other.DstNet;
      }
      if (other.Cid != 0) {
        Cid = other.Cid;
      }
      if (other.CidString.Length != 0) {
        CidString = other.CidString;
      }
      if (other.Normalized != 0) {
        Normalized = other.Normalized;
      }
      if (other.SrcIfName.Length != 0) {
        SrcIfName = other.SrcIfName;
      }
      if (other.SrcIfDesc.Length != 0) {
        SrcIfDesc = other.SrcIfDesc;
      }
      if (other.SrcIfSpeed != 0) {
        SrcIfSpeed = other.SrcIfSpeed;
      }
      if (other.DstIfName.Length != 0) {
        DstIfName = other.DstIfName;
      }
      if (other.DstIfDesc.Length != 0) {
        DstIfDesc = other.DstIfDesc;
      }
      if (other.DstIfSpeed != 0) {
        DstIfSpeed = other.DstIfSpeed;
      }
      if (other.ProtoName.Length != 0) {
        ProtoName = other.ProtoName;
      }
      if (other.RemoteCountry.Length != 0) {
        RemoteCountry = other.RemoteCountry;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Flowmessageenriched.FlowMessage.Types.FlowType) input.ReadEnum();
            break;
          }
          case 16: {
            TimeReceived = input.ReadUInt64();
            break;
          }
          case 24: {
            SamplingRate = input.ReadUInt64();
            break;
          }
          case 32: {
            SequenceNum = input.ReadUInt32();
            break;
          }
          case 40: {
            TimeFlowEnd = input.ReadUInt64();
            break;
          }
          case 50: {
            SrcAddr = input.ReadBytes();
            break;
          }
          case 58: {
            DstAddr = input.ReadBytes();
            break;
          }
          case 72: {
            Bytes = input.ReadUInt64();
            break;
          }
          case 80: {
            Packets = input.ReadUInt64();
            break;
          }
          case 90: {
            SamplerAddress = input.ReadBytes();
            break;
          }
          case 98: {
            NextHop = input.ReadBytes();
            break;
          }
          case 104: {
            NextHopAS = input.ReadUInt32();
            break;
          }
          case 112: {
            SrcAS = input.ReadUInt32();
            break;
          }
          case 120: {
            DstAS = input.ReadUInt32();
            break;
          }
          case 128: {
            SrcNet = input.ReadUInt32();
            break;
          }
          case 136: {
            DstNet = input.ReadUInt32();
            break;
          }
          case 144: {
            SrcIf = input.ReadUInt32();
            break;
          }
          case 152: {
            DstIf = input.ReadUInt32();
            break;
          }
          case 160: {
            Proto = input.ReadUInt32();
            break;
          }
          case 168: {
            SrcPort = input.ReadUInt32();
            break;
          }
          case 176: {
            DstPort = input.ReadUInt32();
            break;
          }
          case 184: {
            IPTos = input.ReadUInt32();
            break;
          }
          case 192: {
            ForwardingStatus = input.ReadUInt32();
            break;
          }
          case 200: {
            IPTTL = input.ReadUInt32();
            break;
          }
          case 208: {
            TCPFlags = input.ReadUInt32();
            break;
          }
          case 216: {
            SrcMac = input.ReadUInt64();
            break;
          }
          case 224: {
            DstMac = input.ReadUInt64();
            break;
          }
          case 232: {
            VlanId = input.ReadUInt32();
            break;
          }
          case 240: {
            Etype = input.ReadUInt32();
            break;
          }
          case 248: {
            IcmpType = input.ReadUInt32();
            break;
          }
          case 256: {
            IcmpCode = input.ReadUInt32();
            break;
          }
          case 264: {
            SrcVlan = input.ReadUInt32();
            break;
          }
          case 272: {
            DstVlan = input.ReadUInt32();
            break;
          }
          case 280: {
            FragmentId = input.ReadUInt32();
            break;
          }
          case 288: {
            FragmentOffset = input.ReadUInt32();
            break;
          }
          case 296: {
            IPv6FlowLabel = input.ReadUInt32();
            break;
          }
          case 304: {
            TimeFlowStart = input.ReadUInt64();
            break;
          }
          case 312: {
            IngressVrfID = input.ReadUInt32();
            break;
          }
          case 320: {
            EgressVrfID = input.ReadUInt32();
            break;
          }
          case 328: {
            BiFlowDirection = input.ReadUInt32();
            break;
          }
          case 336: {
            FlowDirection = input.ReadUInt32();
            break;
          }
          case 344: {
            IPv6ExtensionHeaders = input.ReadUInt32();
            break;
          }
          case 8000: {
            Cid = input.ReadUInt32();
            break;
          }
          case 8010: {
            CidString = input.ReadString();
            break;
          }
          case 8016: {
            Normalized = (global::Flowmessageenriched.FlowMessage.Types.NormalizedType) input.ReadEnum();
            break;
          }
          case 8026: {
            SrcIfName = input.ReadString();
            break;
          }
          case 8034: {
            SrcIfDesc = input.ReadString();
            break;
          }
          case 8040: {
            SrcIfSpeed = input.ReadUInt32();
            break;
          }
          case 8050: {
            DstIfName = input.ReadString();
            break;
          }
          case 8058: {
            DstIfDesc = input.ReadString();
            break;
          }
          case 8064: {
            DstIfSpeed = input.ReadUInt32();
            break;
          }
          case 8074: {
            ProtoName = input.ReadString();
            break;
          }
          case 8082: {
            RemoteCountry = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the FlowMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum FlowType {
        [pbr::OriginalName("FLOWUNKNOWN")] Flowunknown = 0,
        [pbr::OriginalName("SFLOW_5")] Sflow5 = 1,
        [pbr::OriginalName("NETFLOW_V5")] NetflowV5 = 2,
        [pbr::OriginalName("NETFLOW_V9")] NetflowV9 = 3,
        [pbr::OriginalName("IPFIX")] Ipfix = 4,
      }

      public enum NormalizedType {
        [pbr::OriginalName("No")] No = 0,
        [pbr::OriginalName("Yes")] Yes = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
