// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow-messages-enriched.proto

package flowmessageenriched

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FlowMessage_FlowType int32

const (
	FlowMessage_FLOWUNKNOWN FlowMessage_FlowType = 0
	FlowMessage_SFLOW_5     FlowMessage_FlowType = 1
	FlowMessage_NETFLOW_V5  FlowMessage_FlowType = 2
	FlowMessage_NETFLOW_V9  FlowMessage_FlowType = 3
	FlowMessage_IPFIX       FlowMessage_FlowType = 4
)

var FlowMessage_FlowType_name = map[int32]string{
	0: "FLOWUNKNOWN",
	1: "SFLOW_5",
	2: "NETFLOW_V5",
	3: "NETFLOW_V9",
	4: "IPFIX",
}

var FlowMessage_FlowType_value = map[string]int32{
	"FLOWUNKNOWN": 0,
	"SFLOW_5":     1,
	"NETFLOW_V5":  2,
	"NETFLOW_V9":  3,
	"IPFIX":       4,
}

func (x FlowMessage_FlowType) String() string {
	return proto.EnumName(FlowMessage_FlowType_name, int32(x))
}

func (FlowMessage_FlowType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87ac2813ddceac40, []int{0, 0}
}

type FlowMessage_NormalizedType int32

const (
	FlowMessage_No  FlowMessage_NormalizedType = 0
	FlowMessage_Yes FlowMessage_NormalizedType = 1
)

var FlowMessage_NormalizedType_name = map[int32]string{
	0: "No",
	1: "Yes",
}

var FlowMessage_NormalizedType_value = map[string]int32{
	"No":  0,
	"Yes": 1,
}

func (x FlowMessage_NormalizedType) String() string {
	return proto.EnumName(FlowMessage_NormalizedType_name, int32(x))
}

func (FlowMessage_NormalizedType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_87ac2813ddceac40, []int{0, 1}
}

type FlowMessage struct {
	Type          FlowMessage_FlowType `protobuf:"varint,1,opt,name=Type,proto3,enum=flowmessageenriched.FlowMessage_FlowType" json:"Type,omitempty"`
	TimeReceived  uint64               `protobuf:"varint,2,opt,name=TimeReceived,proto3" json:"TimeReceived,omitempty"`
	SequenceNum   uint32               `protobuf:"varint,4,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	SamplingRate  uint64               `protobuf:"varint,3,opt,name=SamplingRate,proto3" json:"SamplingRate,omitempty"`
	FlowDirection uint32               `protobuf:"varint,42,opt,name=FlowDirection,proto3" json:"FlowDirection,omitempty"`
	// Sampler information
	SamplerAddress []byte `protobuf:"bytes,11,opt,name=SamplerAddress,proto3" json:"SamplerAddress,omitempty"`
	// Found inside packet
	TimeFlowStart uint64 `protobuf:"varint,38,opt,name=TimeFlowStart,proto3" json:"TimeFlowStart,omitempty"`
	TimeFlowEnd   uint64 `protobuf:"varint,5,opt,name=TimeFlowEnd,proto3" json:"TimeFlowEnd,omitempty"`
	// Size of the sampled packet
	Bytes   uint64 `protobuf:"varint,9,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Packets uint64 `protobuf:"varint,10,opt,name=Packets,proto3" json:"Packets,omitempty"`
	// Source/destination addresses
	SrcAddr []byte `protobuf:"bytes,6,opt,name=SrcAddr,proto3" json:"SrcAddr,omitempty"`
	DstAddr []byte `protobuf:"bytes,7,opt,name=DstAddr,proto3" json:"DstAddr,omitempty"`
	// Layer 3 protocol (IPv4/IPv6/ARP/...)
	Etype uint32 `protobuf:"varint,30,opt,name=Etype,proto3" json:"Etype,omitempty"`
	// Layer 4 protocol
	Proto uint32 `protobuf:"varint,20,opt,name=Proto,proto3" json:"Proto,omitempty"`
	// Ports for UDP and TCP
	SrcPort uint32 `protobuf:"varint,21,opt,name=SrcPort,proto3" json:"SrcPort,omitempty"`
	DstPort uint32 `protobuf:"varint,22,opt,name=DstPort,proto3" json:"DstPort,omitempty"`
	// Interfaces
	SrcIf uint32 `protobuf:"varint,18,opt,name=SrcIf,proto3" json:"SrcIf,omitempty"`
	DstIf uint32 `protobuf:"varint,19,opt,name=DstIf,proto3" json:"DstIf,omitempty"`
	// Ethernet information
	SrcMac uint64 `protobuf:"varint,27,opt,name=SrcMac,proto3" json:"SrcMac,omitempty"`
	DstMac uint64 `protobuf:"varint,28,opt,name=DstMac,proto3" json:"DstMac,omitempty"`
	// Vlan
	SrcVlan uint32 `protobuf:"varint,33,opt,name=SrcVlan,proto3" json:"SrcVlan,omitempty"`
	DstVlan uint32 `protobuf:"varint,34,opt,name=DstVlan,proto3" json:"DstVlan,omitempty"`
	// 802.1q VLAN in sampled packet
	VlanId uint32 `protobuf:"varint,29,opt,name=VlanId,proto3" json:"VlanId,omitempty"`
	// VRF
	IngressVrfID uint32 `protobuf:"varint,39,opt,name=IngressVrfID,proto3" json:"IngressVrfID,omitempty"`
	EgressVrfID  uint32 `protobuf:"varint,40,opt,name=EgressVrfID,proto3" json:"EgressVrfID,omitempty"`
	// IP and TCP special flags
	IPTos            uint32 `protobuf:"varint,23,opt,name=IPTos,proto3" json:"IPTos,omitempty"`
	ForwardingStatus uint32 `protobuf:"varint,24,opt,name=ForwardingStatus,proto3" json:"ForwardingStatus,omitempty"`
	IPTTL            uint32 `protobuf:"varint,25,opt,name=IPTTL,proto3" json:"IPTTL,omitempty"`
	TCPFlags         uint32 `protobuf:"varint,26,opt,name=TCPFlags,proto3" json:"TCPFlags,omitempty"`
	IcmpType         uint32 `protobuf:"varint,31,opt,name=IcmpType,proto3" json:"IcmpType,omitempty"`
	IcmpCode         uint32 `protobuf:"varint,32,opt,name=IcmpCode,proto3" json:"IcmpCode,omitempty"`
	IPv6FlowLabel    uint32 `protobuf:"varint,37,opt,name=IPv6FlowLabel,proto3" json:"IPv6FlowLabel,omitempty"`
	// Fragments (IPv4/IPv6)
	FragmentId      uint32 `protobuf:"varint,35,opt,name=FragmentId,proto3" json:"FragmentId,omitempty"`
	FragmentOffset  uint32 `protobuf:"varint,36,opt,name=FragmentOffset,proto3" json:"FragmentOffset,omitempty"`
	BiFlowDirection uint32 `protobuf:"varint,41,opt,name=BiFlowDirection,proto3" json:"BiFlowDirection,omitempty"`
	// Autonomous system information
	SrcAS     uint32 `protobuf:"varint,14,opt,name=SrcAS,proto3" json:"SrcAS,omitempty"`
	DstAS     uint32 `protobuf:"varint,15,opt,name=DstAS,proto3" json:"DstAS,omitempty"`
	NextHop   []byte `protobuf:"bytes,12,opt,name=NextHop,proto3" json:"NextHop,omitempty"`
	NextHopAS uint32 `protobuf:"varint,13,opt,name=NextHopAS,proto3" json:"NextHopAS,omitempty"`
	// Prefix size
	SrcNet uint32 `protobuf:"varint,16,opt,name=SrcNet,proto3" json:"SrcNet,omitempty"`
	DstNet uint32 `protobuf:"varint,17,opt,name=DstNet,proto3" json:"DstNet,omitempty"`
	// bwNetFlow enricher fields
	Cid        uint32                     `protobuf:"varint,1000,opt,name=Cid,proto3" json:"Cid,omitempty"`
	CidString  string                     `protobuf:"bytes,1001,opt,name=CidString,proto3" json:"CidString,omitempty"`
	Normalized FlowMessage_NormalizedType `protobuf:"varint,1002,opt,name=Normalized,proto3,enum=flowmessageenriched.FlowMessage_NormalizedType" json:"Normalized,omitempty"`
	// Fields for Interface Usability -- enriched using SNMP
	SrcIfName            string   `protobuf:"bytes,1003,opt,name=SrcIfName,proto3" json:"SrcIfName,omitempty"`
	SrcIfDesc            string   `protobuf:"bytes,1004,opt,name=SrcIfDesc,proto3" json:"SrcIfDesc,omitempty"`
	SrcIfSpeed           uint32   `protobuf:"varint,1005,opt,name=SrcIfSpeed,proto3" json:"SrcIfSpeed,omitempty"`
	DstIfName            string   `protobuf:"bytes,1006,opt,name=DstIfName,proto3" json:"DstIfName,omitempty"`
	DstIfDesc            string   `protobuf:"bytes,1007,opt,name=DstIfDesc,proto3" json:"DstIfDesc,omitempty"`
	DstIfSpeed           uint32   `protobuf:"varint,1008,opt,name=DstIfSpeed,proto3" json:"DstIfSpeed,omitempty"`
	ProtoName            string   `protobuf:"bytes,1009,opt,name=ProtoName,proto3" json:"ProtoName,omitempty"`
	RemoteCountry        string   `protobuf:"bytes,1010,opt,name=RemoteCountry,proto3" json:"RemoteCountry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowMessage) Reset()         { *m = FlowMessage{} }
func (m *FlowMessage) String() string { return proto.CompactTextString(m) }
func (*FlowMessage) ProtoMessage()    {}
func (*FlowMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_87ac2813ddceac40, []int{0}
}

func (m *FlowMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowMessage.Unmarshal(m, b)
}
func (m *FlowMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowMessage.Marshal(b, m, deterministic)
}
func (m *FlowMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowMessage.Merge(m, src)
}
func (m *FlowMessage) XXX_Size() int {
	return xxx_messageInfo_FlowMessage.Size(m)
}
func (m *FlowMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FlowMessage proto.InternalMessageInfo

func (m *FlowMessage) GetType() FlowMessage_FlowType {
	if m != nil {
		return m.Type
	}
	return FlowMessage_FLOWUNKNOWN
}

func (m *FlowMessage) GetTimeReceived() uint64 {
	if m != nil {
		return m.TimeReceived
	}
	return 0
}

func (m *FlowMessage) GetSequenceNum() uint32 {
	if m != nil {
		return m.SequenceNum
	}
	return 0
}

func (m *FlowMessage) GetSamplingRate() uint64 {
	if m != nil {
		return m.SamplingRate
	}
	return 0
}

func (m *FlowMessage) GetFlowDirection() uint32 {
	if m != nil {
		return m.FlowDirection
	}
	return 0
}

func (m *FlowMessage) GetSamplerAddress() []byte {
	if m != nil {
		return m.SamplerAddress
	}
	return nil
}

func (m *FlowMessage) GetTimeFlowStart() uint64 {
	if m != nil {
		return m.TimeFlowStart
	}
	return 0
}

func (m *FlowMessage) GetTimeFlowEnd() uint64 {
	if m != nil {
		return m.TimeFlowEnd
	}
	return 0
}

func (m *FlowMessage) GetBytes() uint64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *FlowMessage) GetPackets() uint64 {
	if m != nil {
		return m.Packets
	}
	return 0
}

func (m *FlowMessage) GetSrcAddr() []byte {
	if m != nil {
		return m.SrcAddr
	}
	return nil
}

func (m *FlowMessage) GetDstAddr() []byte {
	if m != nil {
		return m.DstAddr
	}
	return nil
}

func (m *FlowMessage) GetEtype() uint32 {
	if m != nil {
		return m.Etype
	}
	return 0
}

func (m *FlowMessage) GetProto() uint32 {
	if m != nil {
		return m.Proto
	}
	return 0
}

func (m *FlowMessage) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *FlowMessage) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *FlowMessage) GetSrcIf() uint32 {
	if m != nil {
		return m.SrcIf
	}
	return 0
}

func (m *FlowMessage) GetDstIf() uint32 {
	if m != nil {
		return m.DstIf
	}
	return 0
}

func (m *FlowMessage) GetSrcMac() uint64 {
	if m != nil {
		return m.SrcMac
	}
	return 0
}

func (m *FlowMessage) GetDstMac() uint64 {
	if m != nil {
		return m.DstMac
	}
	return 0
}

func (m *FlowMessage) GetSrcVlan() uint32 {
	if m != nil {
		return m.SrcVlan
	}
	return 0
}

func (m *FlowMessage) GetDstVlan() uint32 {
	if m != nil {
		return m.DstVlan
	}
	return 0
}

func (m *FlowMessage) GetVlanId() uint32 {
	if m != nil {
		return m.VlanId
	}
	return 0
}

func (m *FlowMessage) GetIngressVrfID() uint32 {
	if m != nil {
		return m.IngressVrfID
	}
	return 0
}

func (m *FlowMessage) GetEgressVrfID() uint32 {
	if m != nil {
		return m.EgressVrfID
	}
	return 0
}

func (m *FlowMessage) GetIPTos() uint32 {
	if m != nil {
		return m.IPTos
	}
	return 0
}

func (m *FlowMessage) GetForwardingStatus() uint32 {
	if m != nil {
		return m.ForwardingStatus
	}
	return 0
}

func (m *FlowMessage) GetIPTTL() uint32 {
	if m != nil {
		return m.IPTTL
	}
	return 0
}

func (m *FlowMessage) GetTCPFlags() uint32 {
	if m != nil {
		return m.TCPFlags
	}
	return 0
}

func (m *FlowMessage) GetIcmpType() uint32 {
	if m != nil {
		return m.IcmpType
	}
	return 0
}

func (m *FlowMessage) GetIcmpCode() uint32 {
	if m != nil {
		return m.IcmpCode
	}
	return 0
}

func (m *FlowMessage) GetIPv6FlowLabel() uint32 {
	if m != nil {
		return m.IPv6FlowLabel
	}
	return 0
}

func (m *FlowMessage) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *FlowMessage) GetFragmentOffset() uint32 {
	if m != nil {
		return m.FragmentOffset
	}
	return 0
}

func (m *FlowMessage) GetBiFlowDirection() uint32 {
	if m != nil {
		return m.BiFlowDirection
	}
	return 0
}

func (m *FlowMessage) GetSrcAS() uint32 {
	if m != nil {
		return m.SrcAS
	}
	return 0
}

func (m *FlowMessage) GetDstAS() uint32 {
	if m != nil {
		return m.DstAS
	}
	return 0
}

func (m *FlowMessage) GetNextHop() []byte {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *FlowMessage) GetNextHopAS() uint32 {
	if m != nil {
		return m.NextHopAS
	}
	return 0
}

func (m *FlowMessage) GetSrcNet() uint32 {
	if m != nil {
		return m.SrcNet
	}
	return 0
}

func (m *FlowMessage) GetDstNet() uint32 {
	if m != nil {
		return m.DstNet
	}
	return 0
}

func (m *FlowMessage) GetCid() uint32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *FlowMessage) GetCidString() string {
	if m != nil {
		return m.CidString
	}
	return ""
}

func (m *FlowMessage) GetNormalized() FlowMessage_NormalizedType {
	if m != nil {
		return m.Normalized
	}
	return FlowMessage_No
}

func (m *FlowMessage) GetSrcIfName() string {
	if m != nil {
		return m.SrcIfName
	}
	return ""
}

func (m *FlowMessage) GetSrcIfDesc() string {
	if m != nil {
		return m.SrcIfDesc
	}
	return ""
}

func (m *FlowMessage) GetSrcIfSpeed() uint32 {
	if m != nil {
		return m.SrcIfSpeed
	}
	return 0
}

func (m *FlowMessage) GetDstIfName() string {
	if m != nil {
		return m.DstIfName
	}
	return ""
}

func (m *FlowMessage) GetDstIfDesc() string {
	if m != nil {
		return m.DstIfDesc
	}
	return ""
}

func (m *FlowMessage) GetDstIfSpeed() uint32 {
	if m != nil {
		return m.DstIfSpeed
	}
	return 0
}

func (m *FlowMessage) GetProtoName() string {
	if m != nil {
		return m.ProtoName
	}
	return ""
}

func (m *FlowMessage) GetRemoteCountry() string {
	if m != nil {
		return m.RemoteCountry
	}
	return ""
}

func init() {
	proto.RegisterEnum("flowmessageenriched.FlowMessage_FlowType", FlowMessage_FlowType_name, FlowMessage_FlowType_value)
	proto.RegisterEnum("flowmessageenriched.FlowMessage_NormalizedType", FlowMessage_NormalizedType_name, FlowMessage_NormalizedType_value)
	proto.RegisterType((*FlowMessage)(nil), "flowmessageenriched.FlowMessage")
}

func init() { proto.RegisterFile("flow-messages-enriched.proto", fileDescriptor_87ac2813ddceac40) }

var fileDescriptor_87ac2813ddceac40 = []byte{
	// 868 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0x5d, 0x73, 0xdb, 0x44,
	0x14, 0x86, 0xeb, 0x24, 0xb5, 0xeb, 0xe3, 0xd8, 0x51, 0xb7, 0x6d, 0x38, 0x94, 0xb4, 0x75, 0x4d,
	0x5b, 0xdc, 0xce, 0x34, 0xcc, 0xc0, 0x94, 0x19, 0x2e, 0xb8, 0x70, 0xfc, 0x31, 0x68, 0x48, 0x15,
	0x8f, 0x65, 0x52, 0xb8, 0x62, 0x14, 0x69, 0x6d, 0x34, 0x58, 0x92, 0x91, 0x36, 0x09, 0xe1, 0x87,
	0xf2, 0x1b, 0xf8, 0xfe, 0xfa, 0x05, 0xcc, 0x39, 0xbb, 0x92, 0xa5, 0xc0, 0x0c, 0x57, 0xd1, 0xfb,
	0xbc, 0x7b, 0xde, 0xdd, 0xcd, 0x9e, 0x5d, 0xc3, 0xc1, 0x62, 0x95, 0x5c, 0xbe, 0x8c, 0x64, 0x96,
	0x79, 0x4b, 0x99, 0xbd, 0x94, 0x71, 0x1a, 0xfa, 0x5f, 0xcb, 0xe0, 0x70, 0x9d, 0x26, 0x2a, 0x11,
	0x77, 0xc8, 0x35, 0x66, 0x6e, 0xf5, 0x7e, 0x68, 0x43, 0x6b, 0xb2, 0x4a, 0x2e, 0x5f, 0x6b, 0x2e,
	0x3e, 0x81, 0x9d, 0xf9, 0xd5, 0x5a, 0x62, 0xad, 0x5b, 0xeb, 0x77, 0x3e, 0x78, 0x7e, 0xf8, 0x1f,
	0x35, 0x87, 0xa5, 0xf1, 0xfc, 0x4d, 0x05, 0x33, 0x2e, 0x13, 0x3d, 0xd8, 0x9d, 0x87, 0x91, 0x9c,
	0x49, 0x5f, 0x86, 0x17, 0x32, 0xc0, 0xad, 0x6e, 0xad, 0xbf, 0x33, 0xab, 0x30, 0xd1, 0x85, 0x96,
	0x2b, 0xbf, 0x3d, 0x97, 0xb1, 0x2f, 0x9d, 0xf3, 0x08, 0x77, 0xba, 0xb5, 0x7e, 0x7b, 0x56, 0x46,
	0x94, 0xe2, 0x7a, 0xd1, 0x7a, 0x15, 0xc6, 0xcb, 0x99, 0xa7, 0x24, 0x6e, 0xeb, 0x94, 0x32, 0x13,
	0x4f, 0xa0, 0x4d, 0x73, 0x8f, 0xc2, 0x54, 0xfa, 0x2a, 0x4c, 0x62, 0x7c, 0xc1, 0x39, 0x55, 0x28,
	0x9e, 0x41, 0x87, 0xab, 0x64, 0x3a, 0x08, 0x82, 0x54, 0x66, 0x19, 0xb6, 0xba, 0xb5, 0xfe, 0xee,
	0xec, 0x1a, 0xa5, 0x34, 0x5a, 0x23, 0x15, 0xbb, 0xca, 0x4b, 0x15, 0x3e, 0xe3, 0x29, 0xab, 0x90,
	0x56, 0x9e, 0x83, 0x71, 0x1c, 0xe0, 0x4d, 0x1e, 0x53, 0x46, 0xe2, 0x2e, 0xdc, 0x3c, 0xba, 0x52,
	0x32, 0xc3, 0x26, 0x7b, 0x5a, 0x08, 0x84, 0xc6, 0xd4, 0xf3, 0xbf, 0x91, 0x2a, 0x43, 0x60, 0x9e,
	0x4b, 0x72, 0xdc, 0xd4, 0xa7, 0x55, 0x60, 0x9d, 0x17, 0x96, 0x4b, 0x72, 0x46, 0x99, 0x62, 0xa7,
	0xa1, 0x1d, 0x23, 0x69, 0x8e, 0xb1, 0xa2, 0x33, 0x7a, 0xc8, 0x3b, 0xd6, 0x82, 0xe8, 0x94, 0x8e,
	0x19, 0xef, 0x6a, 0xca, 0xc2, 0xe4, 0x4f, 0x93, 0x54, 0xe1, 0x3d, 0xe6, 0xb9, 0x34, 0xf9, 0xec,
	0xec, 0x6b, 0xc7, 0x48, 0x4a, 0x72, 0x53, 0xdf, 0x5e, 0xa0, 0xd0, 0x49, 0x2c, 0x88, 0x8e, 0x32,
	0x65, 0x2f, 0xf0, 0x8e, 0xa6, 0x2c, 0xc4, 0x3e, 0xd4, 0xdd, 0xd4, 0x7f, 0xed, 0xf9, 0xf8, 0x0e,
	0x6f, 0xcc, 0x28, 0xe2, 0xa3, 0x4c, 0x11, 0x3f, 0xd0, 0x5c, 0x2b, 0xb3, 0x9e, 0xd3, 0x95, 0x17,
	0xe3, 0xe3, 0x62, 0x3d, 0x24, 0xcd, 0x7a, 0xd8, 0xe9, 0x15, 0xeb, 0x61, 0x67, 0x1f, 0xea, 0xf4,
	0xd7, 0x0e, 0xf0, 0x01, 0x1b, 0x46, 0x51, 0x97, 0xd8, 0xf1, 0x92, 0x8e, 0xef, 0x34, 0x5d, 0xd8,
	0x23, 0x7c, 0x8f, 0xdd, 0x0a, 0xa3, 0x13, 0x1b, 0x97, 0x86, 0xf4, 0x75, 0xaf, 0x95, 0x10, 0xed,
	0xcb, 0x9e, 0xce, 0x93, 0x0c, 0xdf, 0xd2, 0xfb, 0x62, 0x21, 0x5e, 0x80, 0x35, 0x49, 0xd2, 0x4b,
	0x2f, 0x0d, 0xc2, 0x78, 0xe9, 0x2a, 0x4f, 0x9d, 0x67, 0x88, 0x3c, 0xe0, 0x5f, 0xdc, 0x24, 0xcc,
	0x8f, 0xf1, 0xed, 0x22, 0x61, 0x7e, 0x2c, 0xee, 0xc3, 0xad, 0xf9, 0x70, 0x3a, 0x59, 0x79, 0xcb,
	0x0c, 0xef, 0xb3, 0x51, 0x68, 0xf2, 0x6c, 0x3f, 0x5a, 0xf3, 0x45, 0x7b, 0xa4, 0xbd, 0x5c, 0xe7,
	0xde, 0x30, 0x09, 0x24, 0x76, 0x37, 0x1e, 0x69, 0xea, 0x52, 0x7b, 0x7a, 0xf1, 0x11, 0x35, 0xdb,
	0xb1, 0x77, 0x26, 0x57, 0xf8, 0x54, 0xf7, 0x7c, 0x05, 0x8a, 0x87, 0x00, 0x93, 0xd4, 0x5b, 0x46,
	0x32, 0x56, 0x76, 0x80, 0xef, 0xf2, 0x90, 0x12, 0xa1, 0x3b, 0x91, 0xab, 0x93, 0xc5, 0x22, 0x93,
	0x0a, 0x9f, 0xf0, 0x98, 0x6b, 0x54, 0xf4, 0x61, 0xef, 0x28, 0xac, 0xde, 0xb1, 0xe7, 0x3c, 0xf0,
	0x3a, 0x36, 0x1d, 0x33, 0x70, 0xb1, 0x53, 0x74, 0xcc, 0xc0, 0x35, 0x1d, 0x33, 0x70, 0x71, 0xaf,
	0xe8, 0x98, 0x81, 0x4b, 0xe7, 0xec, 0xc8, 0xef, 0xd4, 0xa7, 0xc9, 0x1a, 0x77, 0x75, 0x5f, 0x1b,
	0x29, 0x0e, 0xa0, 0x69, 0x3e, 0x07, 0x2e, 0xb6, 0xb9, 0x66, 0x03, 0x4c, 0xa7, 0x39, 0x52, 0xa1,
	0xa5, 0xbb, 0x40, 0x2b, 0xd3, 0x69, 0xc4, 0x6f, 0x6b, 0xae, 0x95, 0xb8, 0x0d, 0xdb, 0xc3, 0x30,
	0xc0, 0x1f, 0x1b, 0x4c, 0xe9, 0x5b, 0x3c, 0x80, 0xe6, 0x30, 0x0c, 0x5c, 0x95, 0x86, 0xf1, 0x12,
	0x7f, 0x22, 0xa3, 0x39, 0xdb, 0x10, 0x31, 0x05, 0x70, 0x92, 0x34, 0xf2, 0x56, 0xe1, 0xf7, 0x32,
	0xc0, 0x9f, 0x1b, 0xfc, 0x02, 0xbe, 0xff, 0xbf, 0x2f, 0xe0, 0xa6, 0x86, 0xdf, 0xc1, 0x52, 0x06,
	0x4d, 0xc8, 0x97, 0xc7, 0xf1, 0x22, 0x89, 0xbf, 0x98, 0x09, 0x0b, 0x52, 0xd8, 0x23, 0x99, 0xf9,
	0xf8, 0x6b, 0xd9, 0x26, 0x22, 0x1e, 0x01, 0xb0, 0x70, 0xd7, 0x52, 0x06, 0xf8, 0x9b, 0xde, 0x48,
	0x09, 0x51, 0x3d, 0xdf, 0x42, 0x8e, 0xff, 0xdd, 0xd4, 0x17, 0xa4, 0xb0, 0x39, 0xfe, 0x8f, 0xb2,
	0x9d, 0xc7, 0xb3, 0xd0, 0xf1, 0x7f, 0x9a, 0xf8, 0x0d, 0xa2, 0x7a, 0x7e, 0x44, 0x38, 0xfe, 0x2f,
	0x53, 0x5f, 0x10, 0xf1, 0x14, 0xda, 0x33, 0x19, 0x25, 0x4a, 0x0e, 0x93, 0xf3, 0x58, 0xa5, 0x57,
	0xf8, 0xb7, 0x1e, 0x52, 0xa5, 0x3d, 0x17, 0x6e, 0xe5, 0xbf, 0x11, 0x62, 0x0f, 0x5a, 0x93, 0xe3,
	0x93, 0x37, 0x9f, 0x3b, 0x9f, 0x39, 0x27, 0x6f, 0x1c, 0xeb, 0x86, 0x68, 0x41, 0xc3, 0x25, 0xf2,
	0xd5, 0x2b, 0xab, 0x26, 0x3a, 0x00, 0xce, 0x78, 0xce, 0xf2, 0xf4, 0x95, 0xb5, 0x55, 0xd1, 0x1f,
	0x5b, 0xdb, 0xa2, 0x49, 0xf7, 0x6c, 0x62, 0x7f, 0x61, 0xed, 0xf4, 0x1e, 0x43, 0xa7, 0xfa, 0x6f,
	0x17, 0x75, 0xd8, 0x72, 0x12, 0xeb, 0x86, 0x68, 0xc0, 0xf6, 0x97, 0x32, 0xb3, 0x6a, 0x47, 0x3d,
	0x68, 0x9e, 0x5d, 0xc6, 0x52, 0xd1, 0xf1, 0x1d, 0xdd, 0x2b, 0x1d, 0xd8, 0xd8, 0x1c, 0xe2, 0xf4,
	0xec, 0xac, 0xce, 0x3f, 0x8c, 0x1f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x65, 0xa5, 0x56, 0xbb,
	0x38, 0x07, 0x00, 0x00,
}
